#!/bin/bash

echyellow "This command will run gradle" \
    "  if it fails, it will run the write metadata command"

echyellow "The goal is to the CI to give the metadata if a step fail" \
    "  so one does not need to run it locally" \
    "  to complete the metadata file"

echyellow "tasks: " \
    "  $*"

gradle $* \
    && echyellow "Everything fine, just keep going" \
    || ERROR=$?

if [ "$ERROR" != "" ]; then
    echyellow "Something ended wrong, let's generate metadata"
    gradle --write-verification-metadata sha256 $*

    export HAS_METADATA=$(git status | grep "verification-metadata.xml")

    if [ "$HAS_METADATA" != "" ]; then

        echyellow "Let's now create a branch and a pull request"

        git checkout -b $CIRCLE_BRANCH-metadata
        git add *verification-metadata.xml
        git commit -m "android: update deps metadata"
        git push -u origin $CIRCLE_BRANCH-metadata

        echyellow "Open the pull request and merge it to have fresh metadata"

    else

        echyellow "The error was not metadata. Wish you luck."

    fi

    echyellow "Now finishing with the original error"
    exit $ERROR
fi
