#!/bin/bash

echyellow "This command will run gradle" \
    "  if it fails, it will run the write metadata command"

echyellow "The goal is to the CI to give the metadata if a step fail" \
    "  so one does not need to run it locally" \
    "  to complete the metadata file"

echyellow "tasks: " \
    "  $*"

gradle $* \
    && echyellow "Everything fine, just keep going" \
    || ERROR=$?

if [ "$ERROR" != "" ]; then
    echyellow "Something ended wrong, let's generate metadata"
    gradle --write-verification-metadata sha256 $*

    export HAS_METADATA=$(git status | grep "verification-metadata.xml")

    if [ "$HAS_METADATA" != "" ]; then

        echyellow "Let's commit the verification metadata"

        eval "$(ssh-agent -s)"
        echo "$GITHUB_CIRCLE_PK" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-add ~/.ssh/id_ed25519

        git config --global user.email "$GITHUB_CIRCLE_EMAIL"
        git config --global user.name "$GITHUB_CIRCLE_NAME"

        git remote get-url origin

        git add *verification-metadata.xml
        git commit -m "android: update deps metadata"
        git push -u origin $CIRCLE_BRANCH

        echyellow "Branch updated, CI will run again"

    else

        echyellow "The error was not metadata. Wish you luck."

    fi

    echyellow "Now finishing with the original error"
    exit $ERROR
fi
