  version_check:
    docker:
      - image: rust
    environment:
      RUST_BACKTRACE: 1
    steps:
      - checkout
      - restore_cache:
          keys:
            - rust-{{ checksum "version/Cargo.toml" }}
      - run:
          name: build
          path: version
          command: cargo build
      - save_cache:
          key: rust-{{ checksum "version/Cargo.toml" }}
          paths:
            - /usr/local/cargo/registry/
      - run:
          name: check_version_changed
          path: version
          command: cargo run -q -- -c

