  test_core:
    docker:
      - image: darakeon/netcore
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - restore_cache:
          keys:
            - 'dotnet-{{ checksum "core/cache_key" }}'
      - run:
          path: core
          name: check vulnerability
          command: |
            RESULT=$(dotnet list package --vulnerable --include-transitive)

            echo "$RESULT"

            NUMBER_OF_PROJECTS=14
            EXPECTED=$(expr $NUMBER_OF_PROJECTS + 4)
            CURRENT=$(echo "$RESULT" | wc -l)

            if [ $CURRENT != $EXPECTED ]; then
                exit 1
            fi
      - run:
          path: core/Tests/Generic
          name: tests generic
          command: dotnet test -v m --no-build
      - run:
          path: core/Tests/Language
          name: tests language
          command: dotnet test -v m --no-build
      - run:
          path: core/Tests/Email
          name: tests email
          command: dotnet test -v m --no-build
      - run:
          path: core/Tests/Exchange
          name: tests exchange
          command: dotnet test -v m --no-build
      - run:
          path: core/Tests/BusinessLogic
          name: tests_business logic
          command: dotnet test -v m --no-build
      - run:
          path: inbox
          name: zip mails
          command: zip inbox.zip *.eml && rm *.eml
      - store_artifacts:
          path: inbox
      - store_artifacts:
          path: core/Tests/log
          destination: log

