  test_core_generic:
    docker:
      - image: darakeon/netcore
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - restore_cache:
          keys:
            - dotnet-{{ checksum "core/cache_key" }}
      - run:
          path: core/Tests/Generic
          name: tests generic
          command: dotnet test -v m --no-build
      - store_artifacts:
          path: core/Tests/log
          destination: log

