  audit_core:
    docker:
      - image: darakeon/netcore
    steps:
      - checkout
      - attach_workspace:
          at: core
      - restore_cache:
          keys:
            - dotnet-{{ checksum "core/cache_key" }}
      - run:
          path: core
          name: check vulnerability
          command: |
            RESULT=$(dotnet list package --vulnerable --include-transitive)

            echo "$RESULT"

            NUMBER_OF_PROJECTS=15
            EXPECTED=$(expr $NUMBER_OF_PROJECTS + 4)
            CURRENT=$(echo "$RESULT" | wc -l)

            if [ $CURRENT != $EXPECTED ]; then
                exit 1
            fi

