  test_android:
    docker:
      - image: darakeon/android
    steps:
      - checkout
      - run:
          name: create empty credentials file
          path: android
          command: echo "storeFile=\nstorePassword=\nkeyAlias=\nkeyPassword=" > keystore.properties
      - restore_cache:
          keys:
            - jars-{{ checksum "ci/android.dockerfile" }}-{{ checksum "android/build.gradle" }}-{{ checksum "android/TestUtils/build.gradle" }}-{{ checksum "android/Lib/build.gradle" }}-{{ checksum "android/App/build.gradle" }}-{{ checksum "android/ErrorLogs/build.gradle" }}
      - run:
          name: project dependencies
          path: android
          command: gradle androidDependencies
      - run:
          name: robolectric dependencies
          path: android
          command: gradle robolectricSdkDownload
      - run:
          name: check vulnerability
          path: android
          command: gradle dependencyCheckAnalyze
      - save_cache:
          key: jars-{{ checksum "ci/android.dockerfile" }}-{{ checksum "android/build.gradle" }}-{{ checksum "android/TestUtils/build.gradle" }}-{{ checksum "android/Lib/build.gradle" }}-{{ checksum "android/App/build.gradle" }}-{{ checksum "android/ErrorLogs/build.gradle" }}
          paths:
            - /var/cache/gradle
      - run:
          name: tests
          path: android
          command: gradle test -x androidDependencies
      - store_artifacts:
          path: android/TestUtils/build/reports
          destination: reports/testUtils
      - store_artifacts:
          path: android/Lib/build/reports
          destination: reports/lib
      - store_artifacts:
          path: android/App/build/reports
          destination: reports/app
      - store_artifacts:
          path: android/ErrorLogs/build/reports
          destination: reports/errorLogs
      - store_artifacts:
          path: android/Lib/log
          destination: log/lib
      - store_artifacts:
          path: android/App/log
          destination: log/app
      - store_test_results:
          path: android/Lib/build/test-results
      - store_test_results:
          path: android/App/build/test-results

