  test_build_robot:
    docker:
      - image: darakeon/netcore
    steps:
      - checkout
      - restore_cache:
          keys:
            - dotnet-{{ checksum "core/Authentication/Authentication.csproj" }}-{{ checksum "core/BusinessLogic/BusinessLogic.csproj" }}-{{ checksum "core/Email/Email.csproj" }}-{{ checksum "core/Entities/Entities.csproj" }}-{{ checksum "core/Generic/Generic.csproj" }}-{{ checksum "core/Language/Language.csproj" }}-{{ checksum "robot/Robot/Robot.csproj" }}
      - run:
          name: dependencies
          command: dotnet restore robot/Robot.sln
      - save_cache:
          key: dotnet-{{ checksum "core/Authentication/Authentication.csproj" }}-{{ checksum "core/BusinessLogic/BusinessLogic.csproj" }}-{{ checksum "core/Email/Email.csproj" }}-{{ checksum "core/Entities/Entities.csproj" }}-{{ checksum "core/Generic/Generic.csproj" }}-{{ checksum "core/Language/Language.csproj" }}-{{ checksum "robot/Robot/Robot.csproj" }}
          paths:
            - ~/.nuget/packages
      - run:
          name: build
          command: dotnet build -c Release robot/Robot.sln --no-restore
      - store_artifacts:
          path: inbox

