  test_build_robot:
    docker:
      - image: darakeon/netcore
    resource_class: small
    environment:
      ASPNETCORE_ENVIRONMENT: circleCI
    steps:
      - checkout
      - restore_cache:
          keys:
            - dotnet-{{ checksum "core/Authentication/Authentication.csproj" }}-{{ checksum "core/BusinessLogic/BusinessLogic.csproj" }}-{{ checksum "core/Email/Email.csproj" }}-{{ checksum "core/Entities/Entities.csproj" }}-{{ checksum "core/Generic/Generic.csproj" }}-{{ checksum "core/Language/Language.csproj" }}-{{ checksum "robot/Robot/Robot.csproj" }}
      - run:
          name: dependencies
          command: dotnet restore robot/Robot.sln
      - save_cache:
          key: dotnet-{{ checksum "core/Authentication/Authentication.csproj" }}-{{ checksum "core/BusinessLogic/BusinessLogic.csproj" }}-{{ checksum "core/Email/Email.csproj" }}-{{ checksum "core/Entities/Entities.csproj" }}-{{ checksum "core/Generic/Generic.csproj" }}-{{ checksum "core/Language/Language.csproj" }}-{{ checksum "robot/Robot/Robot.csproj" }}
          paths:
            - ~/.nuget/packages
      - run:
          name: build
          path: robot/Robot
          command: dotnet publish -c Release Robot.csproj -o /var/robot --no-restore
      - run:
          path: robot
          name: check vulnerability
          command: |
            RESULT=$(dotnet list package --vulnerable --include-transitive)

            echo "$RESULT"

            NUMBER_OF_PROJECTS=9
            EXPECTED=$(expr $NUMBER_OF_PROJECTS + 4)
            CURRENT=$(echo "$RESULT" | wc -l)

            if [ $CURRENT != $EXPECTED ]; then
                exit 1
            fi
      - run:
          name: build
          path: /var/robot
          command: ./DFM.Robot check
      - store_artifacts:
          path: inbox

