  version_change:
    docker:
      - image: rust
    resource_class: small
    environment:
      RUST_BACKTRACE: 1
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "15:78:d5:ca:e6:7d:80:e6:2d:1f:35:a1:f3:9d:1b:48"
      - restore_cache:
          keys:
            - rust-{{ checksum "version/Cargo.toml" }}
      - run:
          name: build
          path: version
          command: cargo build
      - save_cache:
          key: rust-{{ checksum "version/Cargo.toml" }}
          paths:
            - /usr/local/cargo/registry/
      - run:
          name: version change
          path: version
          command: |
            if [ "$VERSION" == "$CIRCLE_BRANCH" ] ; then

              if [ "$NEW_TASKS" == "0" ] ; then
                cargo run -q -- -e
              else
                cargo run -q -- -q $NEW_TASKS
              fi

              git log -2
              git push -u origin $CIRCLE_BRANCH

            else
              cargo run -q -- -c
            fi

