  test_core_language:
    docker:
      - image: darakeon/netcore
    steps:
      - checkout
      - attach_workspace:
          at: core
      - restore_cache:
          keys:
            - dotnet-{{ checksum "core/cache_key" }}
      - run:
          path: core/Tests/Language
          name: tests language
          command: dotnet test -v m --no-build
      - store_artifacts:
          path: core/Tests/log
          destination: log

