  version_change:
    docker:
      - image: rust
    resource_class: small
    environment:
      RUST_BACKTRACE: 1
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "15:78:d5:ca:e6:7d:80:e6:2d:1f:35:a1:f3:9d:1b:48"
      - restore_cache:
          keys:
            - cargo-version-{{ checksum "version/Cargo.toml" }}
      - run:
          name: install
          path: version
          command: |
            if [ ! -f /usr/local/cargo/bin/cargo-audit ]; then
              cargo install cargo-audit
            else
              echo "cargo audit already installed"
            fi
      - run:
          name: audit
          path: version
          command: cargo audit && echo "All OK!"
      - run:
          name: build
          path: version
          command: cargo build
      - save_cache:
          key: cargo-version-{{ checksum "version/Cargo.toml" }}
          paths:
            - /usr/local/cargo/bin/
            - /usr/local/cargo/registry/
      - run:
          name: version change
          path: version
          command: |
            echo "Version: $VERSION"
            echo "Circle branch: $CIRCLE_BRANCH"
            echo "New tasks: $NEW_TASKS"

            if [ "$VERSION" == "$CIRCLE_BRANCH" ] ; then

              if [ "$NEW_TASKS" == "0" ] ; then
                cargo run -q -- -e
              else
                cargo run -q -- -q $NEW_TASKS
              fi

              git log -2
              git push -u origin $CIRCLE_BRANCH

            else
              cargo run -q -- -c
            fi

