  test_android_lib_release:
    docker:
      - image: darakeon/android
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - restore_cache:
          keys:
            - kotlin-{{ checksum "android/cache_key" }}
      - run:
          name: tests lib release
          path: android
          command: gradle :Lib:testReleaseUnitTest -x androidDependencies -x build -x packageRelease -x packageDebug
      - store_artifacts:
          path: android/Lib/log
          destination: log/lib
      - store_test_results:
          path: android/Lib/build/test-results

