  test_android_app_release:
    docker:
      - image: darakeon/android
    steps:
      - checkout
      - attach_workspace:
          at: android
      - restore_cache:
          keys:
            - kotlin-{{ checksum "android/cache_key" }}
      - run:
          name: tests app release
          path: android
          command: gradle-with-metadata :App:testReleaseUnitTest -x androidDependencies -x build -x packageRelease -x packageDebug
      - store_artifacts:
          path: android/App/log
          destination: log/app
      - store_artifacts:
          path: android/gradle/verification-metadata.xml
          destination: verification-metadata.xml
      - store_test_results:
          path: android/App/build/test-results

