  test_android_app_debug:
    docker:
      - image: darakeon/android
    resource_class: large
    steps:
      - checkout
      - attach_workspace:
          at: android
      - restore_cache:
          keys:
            - kotlin-{{ checksum "android/cache_key" }}
      - run:
          name: tests app debug
          path: android
          command: gradle-with-metadata :App:testDebugUnitTest -x androidDependencies -x build -x packageRelease -x packageDebug
      - store_artifacts:
          path: outputs/logs/android
          destination: logs
      - store_artifacts:
          path: android/gradle/verification-metadata.xml
          destination: verification-metadata.xml
      - store_test_results:
          path: android/App/build/test-results

