  build_robot:
    docker:
      - image: darakeon/netcore
    resource_class: small
    environment:
      ASPNETCORE_ENVIRONMENT: circleCI
    steps:
      - checkout
      - attach_workspace:
          at: core
      - run:
          name: set checksums
          command: |
            CS_AUTH=$(md5sum core/Authentication/Authentication.csproj | cut -d' ' -f1)
            CS_BUSI=$(md5sum core/BusinessLogic/BusinessLogic.csproj | cut -d' ' -f1)
            CS_MAIL=$(md5sum core/Email/Email.csproj | cut -d' ' -f1)
            CS_ENTI=$(md5sum core/Entities/Entities.csproj | cut -d' ' -f1)
            CS_GENE=$(md5sum core/Generic/Generic.csproj | cut -d' ' -f1)
            CS_LANG=$(md5sum core/Language/Language.csproj | cut -d' ' -f1)
            CS_EXCH=$(md5sum core/Exchange/Exchange.csproj | cut -d' ' -f1)
            CS_ROBT=$(md5sum robot/Robot/Robot.csproj | cut -d' ' -f1)

            CACHE_KEY=$CS_AUTH-$CS_BUSI-$CS_MAIL-$CS_ENTI-$CS_GENE-$CS_LANG-$CS_EXCH-$CS_ROBT
            echo $CACHE_KEY > robot/cache_key
      - restore_cache:
          keys:
            - dotnet-{{ checksum "robot/cache_key" }}
      - run:
          name: dependencies
          command: dotnet restore robot/Robot.sln
      - save_cache:
          key: dotnet-{{ checksum "robot/cache_key" }}
          paths:
            - ~/.nuget/packages
      - run:
          name: build
          path: robot
          command: dotnet build -c Release Robot.sln --no-restore
      - persist_to_workspace:
          root: robot
          paths:
            - cache_key
            - Robot/bin
            - Robot/obj

