  change_version:
    docker:
      - image: rust
    resource_class: small
    environment:
      RUST_BACKTRACE: 1
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - restore_cache:
          keys:
            - cargo-version-{{ checksum "version/Cargo.toml" }}-{{ checksum "version/Cargo.lock" }}
      - run:
          name: build
          path: version
          command: cargo build
      - run:
          name: version change
          path: version
          command: |
            echo "Version: $VERSION"
            echo "Circle branch: $CIRCLE_BRANCH"
            echo "New tasks: $NEW_TASKS"

            if [ "$VERSION" == "$CIRCLE_BRANCH" ] ; then

              if [ "$NEW_TASKS" == "0" ] ; then
                cargo run -q -- -e
              else
                cargo run -q -- -q $NEW_TASKS
              fi

              git log -2
              git push -u origin $CIRCLE_BRANCH

            else
              cargo run -q -- -c
            fi

