workflows:
  version: 2.1
  build_all:
    jobs:
      - test_ci
      - test_core:
          requires:
            - test_ci
      - test_site:
          requires:
            - test_ci
            - test_core
      - test_browser:
          requires:
            - test_ci
            - test_core
            - test_site
      - test_android:
          requires:
            - test_ci
      - test_build_robot:
          requires:
            - test_ci
            - test_core
      - version_change:
          filters:
            branches:
              only: /^\d+\.\d+\.\d+\.\d+$/
          requires:
            - test_ci
            - test_core
            - test_site
            - test_browser
            - test_android
            - test_build_robot
