workflows:
  version: 2.1
  build_all:
    jobs:
      - trufflehog
      - test_ci:
          requires:
            - trufflehog
      - push_docker_browser:
          requires:
            - test_ci
      - push_docker_android:
          requires:
            - test_ci
      - build_core:
          requires:
            - test_ci
      - audit_core:
          requires:
            - build_core
      - test_core_generic:
          requires:
            - build_core
      - test_core_language:
          requires:
            - build_core
      - test_core_email:
          requires:
            - build_core
      - test_core_exchange:
          requires:
            - build_core
      - test_core_entities:
          requires:
            - build_core
      - test_core_business_logic:
          requires:
            - build_core
      - build_site:
          requires:
            - build_core
      - audit_site:
          requires:
            - build_site
      - test_site:
          requires:
            - build_site
      - audit_test_browser:
          requires:
            - test_ci
      - test_browser:
          requires:
            - audit_test_browser
            - build_site
            - push_docker_browser
      - build_android:
          requires:
            - test_ci
            - push_docker_android
      - audit_android:
          requires:
            - build_android
      - test_android_lib_debug:
          requires:
            - build_android
      - test_android_lib_release:
          requires:
            - build_android
      - test_android_app_debug:
          requires:
            - build_android
      - test_android_app_release:
          requires:
            - build_android
      - build_robot:
          requires:
            - build_core
      - audit_robot:
          requires:
            - build_robot
      - check_robot:
          requires:
            - build_robot
      - build_midna:
          requires:
            - test_ci
      - audit_midna:
          requires:
            - build_midna
      - test_midna:
          requires:
            - build_midna
      - audit_version_changer:
          requires:
            - test_ci
      - change_version:
          filters:
            branches:
              only: /^\d+\.\d+\.\d+\.\d+$/
          requires:
            - trufflehog
            - test_ci
            - push_docker_browser
            - push_docker_android
            - build_core
            - audit_core
            - test_core_generic
            - test_core_language
            - test_core_email
            - test_core_exchange
            - test_core_entities
            - test_core_business_logic
            - build_site
            - audit_site
            - test_site
            - audit_test_browser
            - test_browser
            - build_android
            - audit_android
            - test_android_lib_debug
            - test_android_lib_release
            - test_android_app_debug
            - test_android_app_release
            - build_robot
            - audit_robot
            - check_robot
            - build_midna
            - audit_midna
            - test_midna
            - audit_version_changer
