workflows:
  version: 2.1
  build_all:
    jobs:
      - trufflehog
      - test_ci:
          requires:
            - trufflehog
      - push_docker_browser:
          filters:
            branches:
              only:
                - main
                - /^\d+\.\d+\.\d+\.\d+$/
                - /^dependabot/npm_and_yarn/site/Tests/Browser.+$/
          requires:
            - test_ci
      - push_docker_android:
          filters:
            branches:
              only:
                - main
                - /^\d+\.\d+\.\d+\.\d+$/
                - /^feature/android.+$/
                - /^dependabot/gradle/android/.+$/
          requires:
            - test_ci
      - build_core:
          filters:
            branches:
              only:
                - main
                - /^\d+\.\d+\.\d+\.\d+$/
                - /^feature/core.+$/
                - /^feature/site.+$/
                - /^feature/robot.+$/
                - /^dependabot/nuget/core/.+$/
                - /^dependabot/nuget/site/.+$/
                - /^dependabot/nuget/robot/.+$/
                - /^dependabot/npm_and_yarn/site/Tests/Browser.+$/
          requires:
            - test_ci
      - audit_core:
          filters:
            branches:
              only:
                - main
                - /^\d+\.\d+\.\d+\.\d+$/
                - /^feature/core.+$/
                - /^feature/site.+$/
                - /^feature/robot.+$/
                - /^dependabot/nuget/core/.+$/
                - /^dependabot/nuget/site/.+$/
                - /^dependabot/nuget/robot/.+$/
          requires:
            - build_core
      - test_core_generic:
          filters:
            branches:
              only:
                - main
                - /^\d+\.\d+\.\d+\.\d+$/
                - /^feature/core.+$/
                - /^feature/site.+$/
                - /^feature/robot.+$/
                - /^dependabot/nuget/core/.+$/
                - /^dependabot/nuget/site/.+$/
                - /^dependabot/nuget/robot/.+$/
          requires:
            - build_core
      - test_core_language:
          filters:
            branches:
              only:
                - main
                - /^\d+\.\d+\.\d+\.\d+$/
                - /^feature/core.+$/
                - /^feature/site.+$/
                - /^feature/robot.+$/
                - /^dependabot/nuget/core/.+$/
                - /^dependabot/nuget/site/.+$/
                - /^dependabot/nuget/robot/.+$/
          requires:
            - build_core
      - test_core_email:
          filters:
            branches:
              only:
                - main
                - /^\d+\.\d+\.\d+\.\d+$/
                - /^feature/core.+$/
                - /^feature/site.+$/
                - /^feature/robot.+$/
                - /^dependabot/nuget/core/.+$/
                - /^dependabot/nuget/site/.+$/
                - /^dependabot/nuget/robot/.+$/
          requires:
            - build_core
      - test_core_exchange:
          filters:
            branches:
              only:
                - main
                - /^\d+\.\d+\.\d+\.\d+$/
                - /^feature/core.+$/
                - /^feature/site.+$/
                - /^feature/robot.+$/
                - /^dependabot/nuget/core/.+$/
                - /^dependabot/nuget/site/.+$/
                - /^dependabot/nuget/robot/.+$/
          requires:
            - build_core
      - test_core_entities:
          filters:
            branches:
              only:
                - main
                - /^\d+\.\d+\.\d+\.\d+$/
                - /^feature/core.+$/
                - /^feature/site.+$/
                - /^feature/robot.+$/
                - /^dependabot/nuget/core/.+$/
                - /^dependabot/nuget/site/.+$/
                - /^dependabot/nuget/robot/.+$/
          requires:
            - build_core
      - test_core_business_logic:
          filters:
            branches:
              only:
                - main
                - /^\d+\.\d+\.\d+\.\d+$/
                - /^feature/core.+$/
                - /^feature/site.+$/
                - /^feature/robot.+$/
                - /^dependabot/nuget/core/.+$/
                - /^dependabot/nuget/site/.+$/
                - /^dependabot/nuget/robot/.+$/
          requires:
            - build_core
      - build_site:
          filters:
            branches:
              only:
                - main
                - /^\d+\.\d+\.\d+\.\d+$/
                - /^feature/core.+$/
                - /^feature/site.+$/
                - /^dependabot/nuget/core/.+$/
                - /^dependabot/nuget/site/.+$/
                - /^dependabot/npm_and_yarn/site/Tests/Browser.+$/
          requires:
            - build_core
      - audit_site:
          filters:
            branches:
              only:
                - main
                - /^\d+\.\d+\.\d+\.\d+$/
                - /^feature/core.+$/
                - /^feature/site.+$/
                - /^dependabot/nuget/core/.+$/
                - /^dependabot/nuget/site/.+$/
          requires:
            - build_site
      - test_site:
          filters:
            branches:
              only:
                - main
                - /^\d+\.\d+\.\d+\.\d+$/
                - /^feature/core.+$/
                - /^feature/site.+$/
                - /^dependabot/nuget/core/.+$/
                - /^dependabot/nuget/site/.+$/
          requires:
            - build_site
      - audit_test_browser:
          filters:
            branches:
              only:
                - main
                - /^\d+\.\d+\.\d+\.\d+$/
                - /^feature/core.+$/
                - /^feature/site.+$/
                - /^dependabot/nuget/core/.+$/
                - /^dependabot/nuget/site/.+$/
                - /^dependabot/npm_and_yarn/site/Tests/Browser.+$/
          requires:
            - test_ci
      - test_browser:
          filters:
            branches:
              only:
                - main
                - /^\d+\.\d+\.\d+\.\d+$/
                - /^feature/core.+$/
                - /^feature/site.+$/
                - /^dependabot/nuget/core/.+$/
                - /^dependabot/nuget/site/.+$/
                - /^dependabot/npm_and_yarn/site/Tests/Browser.+$/
          requires:
            - audit_test_browser
            - build_site
            - push_docker_browser
      - build_android:
          filters:
            branches:
              only:
                - main
                - /^\d+\.\d+\.\d+\.\d+$/
                - /^feature/android.+$/
                - /^dependabot/gradle/android/.+$/
          requires:
            - test_ci
            - push_docker_android
      - audit_android:
          filters:
            branches:
              only:
                - main
                - /^\d+\.\d+\.\d+\.\d+$/
                - /^feature/android.+$/
                - /^dependabot/gradle/android/.+$/
          requires:
            - build_android
      - test_android_lib_debug:
          filters:
            branches:
              only:
                - main
                - /^\d+\.\d+\.\d+\.\d+$/
                - /^feature/android.+$/
                - /^dependabot/gradle/android/.+$/
          requires:
            - build_android
      - test_android_lib_release:
          filters:
            branches:
              only:
                - main
                - /^\d+\.\d+\.\d+\.\d+$/
                - /^feature/android.+$/
                - /^dependabot/gradle/android/.+$/
          requires:
            - build_android
      - test_android_app_debug:
          filters:
            branches:
              only:
                - main
                - /^\d+\.\d+\.\d+\.\d+$/
                - /^feature/android.+$/
                - /^dependabot/gradle/android/.+$/
          requires:
            - build_android
      - test_android_app_release:
          filters:
            branches:
              only:
                - main
                - /^\d+\.\d+\.\d+\.\d+$/
                - /^feature/android.+$/
                - /^dependabot/gradle/android/.+$/
          requires:
            - build_android
      - build_robot:
          filters:
            branches:
              only:
                - main
                - /^\d+\.\d+\.\d+\.\d+$/
                - /^feature/robot.+$/
                - /^dependabot/nuget/robot/.+$/
          requires:
            - build_core
      - audit_robot:
          filters:
            branches:
              only:
                - main
                - /^\d+\.\d+\.\d+\.\d+$/
                - /^feature/robot.+$/
                - /^dependabot/nuget/robot/.+$/
          requires:
            - build_robot
      - check_robot:
          filters:
            branches:
              only:
                - main
                - /^\d+\.\d+\.\d+\.\d+$/
                - /^feature/robot.+$/
                - /^dependabot/nuget/robot/.+$/
          requires:
            - build_robot
      - build_midna:
          filters:
            branches:
              only:
                - main
                - /^\d+\.\d+\.\d+\.\d+$/
                - /^feature/midna.+$/
                - /^dependabot/pip/midna/.+$/
          requires:
            - test_ci
      - audit_midna:
          filters:
            branches:
              only:
                - main
                - /^\d+\.\d+\.\d+\.\d+$/
                - /^feature/midna.+$/
                - /^dependabot/pip/midna/.+$/
          requires:
            - build_midna
      - test_midna:
          filters:
            branches:
              only:
                - main
                - /^\d+\.\d+\.\d+\.\d+$/
                - /^feature/midna.+$/
                - /^dependabot/pip/midna/.+$/
          requires:
            - build_midna
      - audit_version_changer:
          filters:
            branches:
              only:
                - main
                - /^\d+\.\d+\.\d+\.\d+$/
                - /^feature/version.+$/
                - /^dependabot/cargo/version/.+$/
          requires:
            - test_ci
      - change_version:
          filters:
            branches:
              only:
                - /^\d+\.\d+\.\d+\.\d+$/
                - /^feature/version.+$/
                - /^dependabot/cargo/version/.+$/
          requires:
            - trufflehog
            - test_ci
            - push_docker_browser
            - push_docker_android
            - build_core
            - audit_core
            - test_core_generic
            - test_core_language
            - test_core_email
            - test_core_exchange
            - test_core_entities
            - test_core_business_logic
            - build_site
            - audit_site
            - test_site
            - audit_test_browser
            - test_browser
            - build_android
            - audit_android
            - test_android_lib_debug
            - test_android_lib_release
            - test_android_app_debug
            - test_android_app_release
            - build_robot
            - audit_robot
            - check_robot
            - build_midna
            - audit_midna
            - test_midna
            - audit_version_changer
