workflows:
  version: 2.1
  build_all:
    jobs:
      - test_ci
      - trufflehog:
          requires:
            - test_ci
      - build_core:
          requires:
            - test_ci
            - trufflehog
      - audit_core:
          requires:
            - build_core
      - test_core_generic:
          requires:
            - build_core
      - test_core_language:
          requires:
            - build_core
      - test_core_email:
          requires:
            - build_core
      - test_core_exchange:
          requires:
            - build_core
      - test_core_business_logic:
          requires:
            - build_core
      - test_site:
          requires:
            - test_ci
            - build_core
            - trufflehog
      - test_browser:
          requires:
            - test_ci
            - build_core
            - test_site
            - trufflehog
      - test_android:
          requires:
            - test_ci
            - trufflehog
      - build_robot:
          requires:
            - test_ci
            - build_core
            - trufflehog
      - version_change:
          filters:
            branches:
              only: /^\d+\.\d+\.\d+\.\d+$/
          requires:
            - test_ci
            - build_core
            - audit_core
            - test_core_generic
            - test_core_language
            - test_core_email
            - test_core_exchange
            - test_core_business_logic
            - test_site
            - test_browser
            - test_android
            - build_robot
            - trufflehog
