workflows:
  version: 2.1

  all:
    jobs:
      - trufflehog:
          filters:
            branches:
              only:
                - main
                - /^\d+\.\d+\.\d+\.\d+$/
      - test_ci:
          requires:
            - trufflehog
      - push_docker_browser:
          requires:
            - test_ci
      - push_docker_android:
          requires:
            - test_ci
      - build_core:
          requires:
            - test_ci
      - audit_core:
          requires:
            - build_core
      - test_core_generic:
          requires:
            - build_core
      - test_core_language:
          requires:
            - build_core
      - test_core_email:
          requires:
            - build_core
      - test_core_exchange:
          requires:
            - build_core
      - test_core_entities:
          requires:
            - build_core
      - test_core_business_logic:
          requires:
            - build_core
      - build_site:
          requires:
            - build_core
      - audit_site:
          requires:
            - build_site
      - test_site:
          requires:
            - build_site
      - audit_test_browser:
          requires:
            - test_ci
      - test_browser:
          requires:
            - audit_test_browser
            - build_site
            - push_docker_browser
      - build_api:
          requires:
            - build_core
      - audit_api:
          requires:
            - build_api
      - test_api:
          requires:
            - build_api
      - build_android:
          requires:
            - test_ci
            - push_docker_android
      - audit_android:
          requires:
            - build_android
      - test_android_lib_debug:
          requires:
            - build_android
      - test_android_lib_release:
          requires:
            - build_android
      - test_android_app_debug:
          requires:
            - build_android
      - test_android_app_release:
          requires:
            - build_android
      - build_robot:
          requires:
            - build_core
      - audit_robot:
          requires:
            - build_robot
      - check_robot:
          requires:
            - build_robot
      - build_midna:
          requires:
            - test_ci
      - audit_midna:
          requires:
            - build_midna
      - test_midna:
          requires:
            - build_midna
      - audit_version_changer:
          requires:
            - test_ci
      - change_version:
          requires:
            - trufflehog
            - test_ci
            - push_docker_browser
            - push_docker_android
            - build_core
            - audit_core
            - test_core_generic
            - test_core_language
            - test_core_email
            - test_core_exchange
            - test_core_entities
            - test_core_business_logic
            - build_site
            - audit_site
            - test_site
            - audit_test_browser
            - test_browser
            - build_android
            - audit_android
            - test_android_lib_debug
            - test_android_lib_release
            - test_android_app_debug
            - test_android_app_release
            - build_robot
            - audit_robot
            - check_robot
            - build_midna
            - audit_midna
            - test_midna
            - audit_version_changer

  core:
    jobs:
      - trufflehog:
          filters:
            branches:
              only:
                - /^feature/core.+$/
                - /^dependabot/nuget/core/.+$/
      - test_ci:
          requires:
            - trufflehog
      - build_core:
          requires:
            - test_ci
      - audit_core:
          requires:
            - build_core
      - test_core_generic:
          requires:
            - build_core
      - test_core_language:
          requires:
            - build_core
      - test_core_email:
          requires:
            - build_core
      - test_core_exchange:
          requires:
            - build_core
      - test_core_entities:
          requires:
            - build_core
      - test_core_business_logic:
          requires:
            - build_core

  site:
    jobs:
      - trufflehog:
          filters:
            branches:
              only:
                - /^feature/site.+$/
                - /^dependabot/nuget/site/.+$/
      - test_ci:
          requires:
            - trufflehog
      - push_docker_browser:
          requires:
            - test_ci
      - build_core:
          requires:
            - test_ci
      - build_site:
          requires:
            - build_core
      - audit_site:
          requires:
            - build_site
      - test_site:
          requires:
            - build_site
      - test_browser:
          requires:
            - build_site
            - push_docker_browser

  browser:
    jobs:
      - trufflehog:
          filters:
            branches:
              only:
                - /^dependabot/npm_and_yarn/site/Tests/Browser.+$/
      - test_ci:
          requires:
            - trufflehog
      - push_docker_browser:
          requires:
            - test_ci
      - build_core:
          requires:
            - test_ci
      - build_site:
          requires:
            - build_core
      - audit_test_browser:
          requires:
            - test_ci
      - test_browser:
          requires:
            - build_site
            - audit_test_browser
            - push_docker_browser
            - build_core
            - build_site

  robot:
    jobs:
      - trufflehog:
          filters:
            branches:
              only:
                - /^feature/robot.+$/
                - /^dependabot/nuget/robot/.+$/
      - test_ci:
          requires:
            - trufflehog
      - build_core:
          requires:
            - test_ci
      - build_robot:
          requires:
            - build_core
      - audit_robot:
          requires:
            - build_robot
      - check_robot:
          requires:
            - build_robot

  api:
    jobs:
      - trufflehog:
          filters:
            branches:
              only:
                - /^feature/api.+$/
                - /^dependabot/nuget/api/.+$/
      - test_ci:
          requires:
            - trufflehog
      - build_core:
          requires:
            - test_ci
      - build_api:
          requires:
            - build_core
      - audit_api:
          requires:
            - build_api
      - test_api:
          requires:
            - build_api

  android:
    jobs:
      - trufflehog:
          filters:
            branches:
              only:
                - /^feature/android.+$/
                - /^dependabot/gradle/android/.+$/
      - test_ci:
          requires:
            - trufflehog
      - push_docker_android:
          requires:
            - test_ci
      - build_android:
          requires:
            - test_ci
            - push_docker_android
      - audit_android:
          requires:
            - build_android
      - test_android_lib_debug:
          requires:
            - build_android
      - test_android_lib_release:
          requires:
            - build_android
      - test_android_app_debug:
          requires:
            - build_android
      - test_android_app_release:
          requires:
            - build_android

  midna:
    jobs:
      - trufflehog:
          filters:
            branches:
              only:
                - /^feature/midna.+$/
                - /^dependabot/pip/midna/.+$/
      - test_ci:
          requires:
            - trufflehog
      - build_midna:
          requires:
            - test_ci
      - audit_midna:
          requires:
            - build_midna
      - test_midna:
          requires:
            - build_midna

  version_:
    jobs:
      - trufflehog:
          filters:
            branches:
              only:
                - /^feature/version.+$/
                - /^dependabot/cargo/version/.+$/
      - test_ci:
          requires:
            - trufflehog
      - audit_version_changer:
          requires:
            - test_ci
      - change_version:
          requires:
            - test_ci
            - audit_version_changer
