version: 2.1

# Do not change file .circleci/config.yml
# the folder .circleci/pieces has the parts of the script
# go to .git > hooks and create a file called pre-commit
# with this content (without first '#' sign)

# #!/bin/sh
# ./.circleci/assembly.sh


jobs:
  workflow_ran:
    docker:
      - image: cimg/base:current
    steps:
      - run: echo "Now it can be merged into version branch!"
