  push_docker_rust_github_cli:
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install make
          command: apk add make
      - run:
          name: Login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run:
          name: Build images
          path: architecture/ci
          command: make build_rust_github_cli PUSH=1

