  build_core:
    docker:
      - image: darakeon/netcore
    steps:
      - checkout
      - run:
          name: set checksums
          command: |
            cat core/*/*.csproj > core_cache_key
            CS_CORE=$(md5sum core_cache_key | cut -d' ' -f1)

            cat core/*/*/*.csproj >> tests_cache_key
            CS_TEST=$(md5sum tests_cache_key | cut -d' ' -f1)

            CACHE_KEY=$CS_CORE-$CS_TEST
            echo $CACHE_KEY > core/cache_key
      - restore_cache:
          keys:
            - dotnet-{{ checksum "core/cache_key" }}
      - run:
          name: dependencies
          command: dotnet restore core/Core.sln
      - save_cache:
          key: dotnet-{{ checksum "core/cache_key" }}
          paths:
            - ~/.nuget/packages
      - run:
          name: build
          command: dotnet build -c Debug core/Core.sln --no-restore
      - persist_to_workspace:
          root: core
          paths:
            - cache_key
            - "*/bin"
            - "*/obj"
            - "Tests/*/bin"
            - "Tests/*/obj"

