  test_core_email:
    docker:
      - image: darakeon/netcore:alpine-net8
    steps:
      - checkout
      - attach_workspace:
          at: core
      - restore_cache:
          keys:
            - dotnet-{{ checksum "core/core_cache_key" }}
      - run:
          path: core/Tests/Email
          name: tests email
          command: dotnet test -v m --no-build
      - run:
          path: outputs/inbox
          name: zip mails
          command: zip inbox.zip *.eml && rm *.eml
      - store_artifacts:
          path: outputs/inbox
      - store_artifacts:
          path: outputs/logs/core
          destination: logs

