  test_core_entities:
    docker:
      - image: darakeon/netcore:alpine-net8
    steps:
      - checkout
      - attach_workspace:
          at: core
      - restore_cache:
          keys:
            - dotnet-{{ checksum "core/core_cache_key" }}
      - run:
          path: core/Tests/Entities
          name: tests entities
          command: dotnet test -v m --no-build
      - store_artifacts:
          path: outputs/logs/core
          destination: logs

