  build_site:
    docker:
      - image: darakeon/netcore
    steps:
      - checkout
      - attach_workspace:
          at: core
      - run:
          name: set checksums
          command: |
            cat core/*/*.csproj > core_cache_key
            CS_CORE=$(md5sum core_cache_key | cut -d' ' -f1)

            CS_MVC_=$(md5sum site/MVC/MVC.csproj | cut -d' ' -f1)
            CS_TMVC=$(md5sum site/Tests/MVC/MVC.Tests.csproj | cut -d' ' -f1)

            CACHE_KEY=$CS_CORE-$CS_MVC_-$CS_TMVC
            echo $CACHE_KEY > site/cache_key
      - restore_cache:
          keys:
            - dotnet-{{ checksum "site/cache_key" }}
      - run:
          name: dependencies
          command: dotnet restore site/Site.sln
      - save_cache:
          key: dotnet-{{ checksum "site/cache_key" }}
          paths:
            - ~/.nuget/packages
      - run:
          name: build
          command: dotnet build -c Debug site/Site.sln --no-restore
      - persist_to_workspace:
          root: site
          paths:
            - cache_key
            - MVC/bin
            - MVC/obj
            - Tests/MVC/bin
            - Tests/MVC/obj

