  test_site:
    docker:
      - image: darakeon/netcore:alpine-net8
    steps:
      - checkout
      - attach_workspace:
          at: site
      - restore_cache:
          keys:
            - dotnet-{{ checksum "site/site_cache_key" }}
      - run:
          path: site/Tests/MVC
          name: tests mvc
          command: dotnet test -v m --no-build
      - store_artifacts:
          path: outputs/inbox
      - store_artifacts:
          path: site/Tests/log
          destination: log

