  audit_test_browser:
    docker:
      - image: darakeon/dfm-browser-tests
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - restore_cache:
          keys:
            - node-{{ checksum "site/Tests/Browser/package.json" }}-{{ checksum "site/Tests/Browser/package-lock.json" }}
      - run:
          name: dependencies node
          path: site/Tests/Browser
          command: npm install
      - run:
          name: check for unexpected changes
          command: |
            DIFF=$(git diff)
            if [ "$DIFF" != "" ]; then
              echo "Something has being changed, it should not happen:"
              echo "$DIFF"
              exit 1
            fi
      - save_cache:
          key: node-{{ checksum "site/Tests/Browser/package.json" }}-{{ checksum "site/Tests/Browser/package-lock.json" }}
          paths:
            - site/Tests/Browser/node_modules
      - run:
          name: check_dependencies node
          path: site/Tests/Browser
          command: npm audit
      - store_artifacts:
          path: /root/.npm/_logs/
      - store_artifacts:
          path: /root/.npm/eresolve-report.txt
      - store_artifacts:
          path: site/Tests/Browser/package-lock.json

