  test_browser:
    docker:
      - image: darakeon/dfm-browser-tests:sqlite-ok
    steps:
      - checkout
      - attach_workspace:
          at: core
      - attach_workspace:
          at: site
      - restore_cache:
          keys:
            - dotnet-{{ checksum "site/site_cache_key" }}
      - restore_cache:
          keys:
            - dotnet-libman-{{ checksum "site/MVC/libman.json" }}
      - run:
          name: dependencies client
          path: site/MVC
          command: libman restore
      - save_cache:
          key: dotnet-libman-{{ checksum "site/MVC/libman.json" }}
          paths:
            - site/MVC/Assets/libs
      - run:
          name: publish site
          path: site/MVC
          command: dotnet publish -c Release MVC.csproj -o ../Tests/Browser/server --no-restore
      - save_cache:
          key: dotnet-browser-server-{{ checksum "site/Tests/Browser/server/DFM.MVC" }}
          paths:
            - site/Tests/Browser/server
      - restore_cache:
          keys:
            - node-{{ checksum "site/Tests/Browser/package.json" }}-{{ checksum "site/Tests/Browser/package-lock.json" }}
      - run:
          name: tests browser
          command: .circleci/browser/run-tests.sh
      - store_artifacts:
          path: outputs/logs
      - store_artifacts:
          path: site/Tests/Browser/server/tests.db
      - store_artifacts:
          path: outputs/inbox
      - store_artifacts:
          path: outputs/s3

  test_browser_wait_fix:
    docker:
      - image: darakeon/dfm-browser-tests
    steps:
      - checkout
      - attach_workspace:
          at: core
      - attach_workspace:
          at: site
      - restore_cache:
          keys:
            - dotnet-{{ checksum "site/site_cache_key" }}
      - restore_cache:
          keys:
            - dotnet-libman-{{ checksum "site/MVC/libman.json" }}
      - restore_cache:
          keys:
            - dotnet-browser-server-{{ checksum "site/Tests/Browser/server/DFM.MVC" }}
      - restore_cache:
          keys:
            - node-{{ checksum "site/Tests/Browser/package.json" }}-{{ checksum "site/Tests/Browser/package-lock.json" }}
      - run:
          name: clear database
          path: site/Tests/Browser/server
          command: rm tests.db
      - run:
          name: tests browser
          command: .circleci/browser/run-tests.sh
      - store_artifacts:
          path: outputs/logs
      - store_artifacts:
          path: site/Tests/Browser/server/tests.db
      - store_artifacts:
          path: outputs/inbox
      - store_artifacts:
          path: outputs/s3

