  build_api:
    docker:
      - image: darakeon/netcore:alpine-net8
    steps:
      - checkout
      - attach_workspace:
          at: core
      - run:
          name: set checksums
          command: |
            cat core/*/*.csproj > core_cache_key
            CS_CORE=$(md5sum core_cache_key | cut -d' ' -f1)

            CS_API_=$(md5sum api/API/API.csproj | cut -d' ' -f1)
            CS_TAPI=$(md5sum api/Tests/API/API.Tests.csproj | cut -d' ' -f1)

            API_CACHE_KEY=$CS_CORE-$CS_API_-$CS_TAPI
            echo $API_CACHE_KEY > api/api_cache_key
      - restore_cache:
          keys:
            - dotnet-{{ checksum "api/api_cache_key" }}
      - run:
          name: dependencies
          command: dotnet restore api/API.sln
      - save_cache:
          key: dotnet-{{ checksum "api/api_cache_key" }}
          paths:
            - ~/.nuget/packages
      - run:
          name: build
          command: dotnet build -c Debug api/API.sln --no-restore
      - persist_to_workspace:
          root: api
          paths:
            - api_cache_key
            - API/bin
            - API/obj
            - Tests/API/bin
            - Tests/API/obj

