  build_android:
    docker:
      - image: darakeon/android:gradle8.13-jdk17
    resource_class: large
    steps:
      - checkout
      - run:
          name: create empty credentials file
          path: android
          command: echo "storeFile=\nstorePassword=\nkeyAlias=\nkeyPassword=" > keystore.properties
      - run:
          name: set checksums
          command: |
            KT_DOCK=$(md5sum architecture/ci/android.dockerfile | cut -d' ' -f1)
            KT_MAIN=$(md5sum android/build.gradle | cut -d' ' -f1)
            KT_UTIL=$(md5sum android/TestUtils/build.gradle | cut -d' ' -f1)
            KT_LIBR=$(md5sum android/Lib/build.gradle | cut -d' ' -f1)
            KT_APPL=$(md5sum android/App/build.gradle | cut -d' ' -f1)
            KT_ERRO=$(md5sum android/ErrorLogs/build.gradle | cut -d' ' -f1)

            ANDROID_CACHE_KEY=$KT_DOCK-$KT_MAIN-$KT_UTIL-$KT_LIBR-$KT_APPL-$KT_ERRO
            echo $ANDROID_CACHE_KEY > android/android_cache_key
      - restore_cache:
          keys:
            - kotlin-{{ checksum "android/android_cache_key" }}
      - run:
          name: project dependencies
          path: android
          command: gradle-with-metadata --no-daemon androidDependencies
      - save_cache:
          key: kotlin-{{ checksum "android/android_cache_key" }}
          paths:
            - /var/cache/gradle
            - /root/.m2/repository
      - run:
          name: build
          path: android
          command: gradle-with-metadata --no-daemon build -x test -x androidDependencies -x packageRelease -x packageDebug
      - run:
          name: configure
          path: android
          command: gradle-with-metadata --no-daemon configure
      - store_artifacts:
          path: android/build/reports
          destination: reports/main
      - store_artifacts:
          path: android/TestUtils/build/reports
          destination: reports/testUtils
      - store_artifacts:
          path: android/Lib/build/reports
          destination: reports/lib
      - store_artifacts:
          path: android/App/build/reports
          destination: reports/app
      - store_artifacts:
          path: android/ErrorLogs/build/reports
          destination: reports/errorLogs
      - store_artifacts:
          path: android/gradle/verification-metadata.xml
          destination: verification-metadata.xml
      - persist_to_workspace:
          root: android
          paths:
            - android_cache_key
            - keystore.properties
            - build
            - Lib/build
            - App/build
            - ErrorLogs/build
            - TestUtils/build

