  test_android_lib_debug:
    docker:
      - image: darakeon/android:gradle8.13-jdk17
    resource_class: large
    steps:
      - checkout
      - attach_workspace:
          at: android
      - restore_cache:
          keys:
            - kotlin-{{ checksum "android/android_cache_key" }}
      - run:
          name: tests lib debug
          path: android
          command: gradle-with-metadata :Lib:testDebugUnitTest -x androidDependencies -x build -x packageRelease -x packageDebug
      - store_artifacts:
          path: outputs/logs/android
          destination: logs
      - store_artifacts:
          path: android/gradle/verification-metadata.xml
          destination: verification-metadata.xml
      - store_test_results:
          path: android/Lib/build/test-results

