  build_robot:
    docker:
      - image: darakeon/netcore
    resource_class: small
    environment:
      ASPNETCORE_ENVIRONMENT: circleCI
    steps:
      - checkout
      - attach_workspace:
          at: core
      - run:
          name: set checksums
          command: |
            cat core/*/*.csproj > core_cache_key
            CS_CORE=$(md5sum core_cache_key | cut -d' ' -f1)

            CS_ROBT=$(md5sum robot/Robot/Robot.csproj | cut -d' ' -f1)

            CACHE_KEY=$CS_CORE-$CS_ROBT
            echo $CACHE_KEY > robot/cache_key
      - restore_cache:
          keys:
            - dotnet-{{ checksum "robot/cache_key" }}
      - run:
          name: dependencies
          command: dotnet restore robot/Robot.sln
      - save_cache:
          key: dotnet-{{ checksum "robot/cache_key" }}
          paths:
            - ~/.nuget/packages
      - run:
          name: build
          path: robot
          command: dotnet build -c Release Robot.sln --no-restore
      - persist_to_workspace:
          root: robot
          paths:
            - cache_key
            - Robot/bin
            - Robot/obj

