  audit_robot:
    docker:
      - image: darakeon/netcore:alpine-net8
    resource_class: small
    environment:
      ASPNETCORE_ENVIRONMENT: circleCI
    steps:
      - checkout
      - attach_workspace:
          at: core
      - attach_workspace:
          at: robot
      - restore_cache:
          keys:
            - dotnet-{{ checksum "robot/robot_cache_key" }}
      - run:
          path: robot
          name: check vulnerability
          command: |
            RESULT=$(dotnet list package --vulnerable --include-transitive)
            NO_VULNERABLE=$(echo "$RESULT" | grep 'has no vulnerable')

            echo "$RESULT"

            NUMBER_OF_PROJECTS=$(cat Robot.sln | grep .csproj | wc -l)
            CURRENT=$(echo "$NO_VULNERABLE" | wc -l)

            if [ $CURRENT != $NUMBER_OF_PROJECTS ]; then
                exit 1
            fi

