  check_robot:
    docker:
      - image: darakeon/netcore
    resource_class: small
    environment:
      ASPNETCORE_ENVIRONMENT: circleCI
    steps:
      - checkout
      - attach_workspace:
          at: robot
      - restore_cache:
          keys:
            - dotnet-{{ checksum "robot/robot_cache_key" }}
      - run:
          name: check
          path: robot/Robot/bin/Release/net8.0
          command: ./DFM.Robot check

