  audit_midna:
    docker:
      - image: python:3.13 # if change, remember to change save_cache
    steps:
      - checkout
      #- attach_workspace:
      #    at: midna
      - restore_cache:
          keys:
            - python-3-13-{{ checksum "midna/src/requirements.txt" }}
      - run:
          path: midna/src
          name: check vulnerability
          command: python -m pip_audit

