  test_midna:
    docker:
      - image: python:3.13 # if change, remember to change save_cache
    steps:
      - checkout
      #- attach_workspace:
      #    at: midna
      - restore_cache:
          keys:
            - python-3-13-{{ checksum "midna/src/requirements.txt" }}
      - run:
          path: midna
          name: run tests
          command: |
            set -o allexport
            source env/example.env
            set +o allexport
            export LOGS_OFF=1
            cd src
            python manage.py test deleted_users
            python manage.py test plans

