  export_terms:
    docker:
      - image: darakeon/dfm-migrator-ci
        environment:
          DATABASE_HOST: 127.0.0.1
          DATABASE_NAME: dfm
          DATABASE_USER: root
          DATABASE_PASS: password
          RUN_DATA: 1
          VERSION: 13.0.0.0
      - image: mysql
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: dfm
    steps:
      - run:
          name: run script
          path: /var/db
          command: python upgrade/main.py
      - checkout
      - run:
          name: update terms README
          path: terms
          command: python update_contract_readme.py
      - run:
          name: commit readme if changed
          path: terms
          command: |
            DIFF=$(git diff)
            if [ "$DIFF" == "" ]; then
              echo "Nothing to commit"
            else
              source config-git
              git add README.md
              git commit -m "legal: add new contract to git"
              git push
            fi
      - run:
          name: update terms S3
          path: terms
          command: python update_contract_html.py
      - store_artifacts:
          path: terms/README.md

