  export_terms:
    docker:
      - image: darakeon/sql-runner:ci
        environment:
          DATABASE_HOST: 127.0.0.1
          DATABASE_NAME: dfm
          DATABASE_USER: root
          DATABASE_PASS: password
          RUN_DATA: 1
          VERSION: 13.0.0.0
      - image: mysql
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: dfm
    steps:
      - run:
          name: run script
          path: /var/db
          command: python upgrade/main.py
      - checkout
      - run:
          name: update terms
          path: terms
          command: python update_contract.py

