  export_terms:
    docker:
      - image: darakeon/dfm-migrator-ci
        environment:
          DATABASE_HOST: 127.0.0.1
          DATABASE_NAME: dfm
          DATABASE_USER: root
          DATABASE_PASS: password
          RUN_DATA: 1
      - image: mysql
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: dfm
    steps:
      - run:
          name: run script
          path: /var/db
          command: python upgrade/main.py
      - checkout
      - run:
          name: update terms README
          path: terms
          command: |
            export VERSION=$CIRCLE_BRANCH
            python update_contract_readme.py
      - run:
          name: update terms html
          path: terms
          command: |
            export VERSION=$CIRCLE_BRANCH
            python update_contract_html.py
      - run:
          name: upload terms html to S3
          path: terms
          command: |
            DIFF=$(git diff)
            if [ "$DIFF" == "" ]; then
              echo "Nothing to upload"
            else
              python publish_contract_html.py
            fi
      - run:
          name: commit readme if changed
          path: terms
          command: |
            DIFF=$(git diff)
            if [ "$DIFF" == "" ]; then
              echo "Nothing to commit"
            else
              source config-git
              git add README.md
              git add terms.html
              git commit -m "legal: add new contract to git"
              git push --force-with-lease
            fi
      - store_artifacts:
          path: terms/README.md

