  dependabot_auto_approve:
    docker:
      - image: darakeon/github-cli
    resource_class: small
    environment:
      TARGET_BRANCH: "15.0.0.0"
    steps:
      - checkout
      - run:
          name: check last ci succeeded for target branch
          path: .circleci/auto-merge
          command: |
            python check_version_pipeline.py
      - run:
          name: Make folder
          path: .circleci/auto-merge
          command: |
            mkdir prs
      - run:
          name: List PRs
          path: .circleci/auto-merge
          command: |
            gh pr list --base $TARGET_BRANCH --author app/dependabot --state open --json author,autoMergeRequest,baseRefName,closed,commits,headRefName,headRepository,headRepositoryOwner,id,isCrossRepository,isDraft,labels,number,state,statusCheckRollup > prs/list.json
      - run:
          name: Get PR to merge
          path: .circleci/auto-merge
          command: |
            python get_next_auto_merge.py prs/list.json > prs/chosen
      - run:
          name: Merge PR
          path: .circleci/auto-merge
          command: |
            export EXISTS=$(git branch --all | grep dependabots)
            if [ "$EXISTS" == "" ]; then
              git branch dependabots origin/$TARGET_BRANCH
              git push origin dependabots
            fi

            export PR=$(tail -n 1 prs/chosen)
            if [ "$PR" != "" ]; then
              gh pr comment $PR --body "@dependabot recreate"
              gh pr edit --base dependabots $PR
              gh pr merge --auto --rebase $PR
            else
              echo "No PRs to merge"
            fi
      - store_artifacts:
          path: .circleci/auto-merge/prs
          destination: prs

