  dependabot_auto_aprove:
    docker:
      - image: darakeon/github-cli
    resource_class: small
    steps:
      - checkout
      - run:
          name: Make folder
          command: |
            mkdir prs
      - run:
          name: List PRs
          command: |
            gh pr list --base $CIRCLE_BRANCH --author app/dependabot --state open --json author,autoMergeRequest,baseRefName,closed,commits,headRefName,headRepository,headRepositoryOwner,id,isCrossRepository,isDraft,labels,number,state,statusCheckRollup > prs/list.json
      - run:
          name: Get PR to merge
          command: |
            python .circleci/auto-merge/get_next_auto_merge.py prs/list.json > prs/chosen
      - run:
          name: Merge PR
          command: |
            export PR=$(tail -n 1 prs/chosen)
            if [ "$PR" != "" ]; then
              gh pr merge --auto --rebase $PR
            else
              echo "No PRs to merge"
            fi
      - store_artifacts:
          path: prs
          destination: prs

