  change_version:
    docker:
      - image: darakeon/rust-github-cli
    resource_class: small
    environment:
      RUST_BACKTRACE: 1
    steps:
      - checkout
      #- attach_workspace:
      #    at: version
      - restore_cache:
          keys:
            - cargo-version-{{ checksum "version/Cargo.toml" }}-{{ checksum "version/Cargo.lock" }}
      - run:
          name: build
          path: version
          command: cargo build
      - run:
          name: version change
          path: version
          command: |
            if [ "$CIRCLE_BRANCH" == "feature/version/new" ]; then
              echo "Already in the new version branch"
            else
              export GIT_EMAIL=$GITHUB_CIRCLE_EMAIL
              export GIT_NAME=$GITHUB_CIRCLE_NAME
              cargo run -q -- -q 1
            fi
      - run:
          name: push
          path: architecture/ci
          command: |
            DIFF=$(git diff origin/$CIRCLE_BRANCH)
            if [ "$DIFF" == "" ]; then
              echo "Nothing to push"
            else
              source config-git
              merge-by-branch feature/version/new version
            fi
      - run:
          name: release
          command: |
            if [ "$CIRCLE_BRANCH" == "feature/version/new" ]; then
              echo "No release"
            else
              circleci run release log \
                --environment-name=DFM \
                --component-name=$CIRCLE_JOB \
                --target-version=$CIRCLE_BRANCH
            fi

