  publish_android:
    docker:
      - image: darakeon/android-publish
    steps:
      - checkout
      - attach_workspace:
          at: android
      - restore_cache:
          keys:
            - kotlin-{{ checksum "android/android_cache_key" }}
      - run:
          name: Create file keystore properties
          path: android
          command: echo ${ANDROID_BUNDLE_PROPERTIES} | base64 -d > keystore.properties
      - run:
          name: Create file keystore
          path: /var/keys
          command: echo ${ANDROID_BUNDLE_KEYSTORE} | base64 -d > keon.keystore
      - run:
          name: Build bundle
          path: android
          command: gradle --no-daemon :app:bundleRelease -Phide-test-deps
      - run:
          name: Remove file keystore
          path: /var/keys
          command: rm keon.keystore
      - run:
          name: Remove file keystore properties
          path: android
          command: rm keystore.properties
      - run:
          name: Publish to Play Store
          command: |
            export ANDROID_BUNDLE=android/App/build/outputs/bundle/release/App-release.aab
            export ANDROID_APP_VERSION=$(git branch --show-current)
            python3 .circleci/android/publish.py
      - store_artifacts:
          path: android/App/build/outputs/bundle/release/
          destination: bundle

