  browser:
    jobs:
      - trufflehog:
          filters:
            branches:
              only:
                - /^feature/browser/.+$/
                - /^fix/browser/.+$/
                - /^dependabot/npm_and_yarn/site/Tests/Browser.+$/
      - test_ci:
          requires:
            - trufflehog
      - push_docker_browser:
          requires:
            - test_ci
      - build_core:
          requires:
            - test_ci
      - build_site:
          requires:
            - build_core
      - audit_test_browser:
          requires:
            - test_ci
            - push_docker_browser
      - test_browser:
          requires:
            - build_site
            - audit_test_browser
            - push_docker_browser
      - workflow_ran:
          requires:
            - trufflehog
            - test_ci
            - push_docker_browser
            - build_core
            - build_site
            - audit_test_browser
            - test_browser

