  db:
    jobs:
      - trufflehog:
          filters:
            branches:
              only:
                - /^feature/db/.+$/
                - /^fix/db/.+$/
      - test_ci:
          requires:
            - trufflehog
      - push_docker_migrator_ci:
          requires:
            - test_ci
      - export_terms:
          requires:
            - test_ci
            - push_docker_migrator_ci
      - workflow_ran:
          requires:
            - trufflehog
            - test_ci
            - push_docker_migrator_ci
            - export_terms

