  ci:
    jobs:
      - trufflehog:
          filters:
            branches:
              only:
                - /^feature/ci/.+$/
                - /^fix/ci/.+$/
      - test_ci:
          requires:
            - trufflehog
      - dependabot_auto_aprove
      - workflow_ran:
          requires:
            - test_ci
