  independabot:
    when:
      equal: ["scheduled_pipeline", << pipeline.trigger_source >>]
    jobs:
      - dependabot_auto_approve:
          filters:
            branches:
              only:
                - main
