// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.6.1.0
//      SpecFlow Generator Version:1.6.0.0
//      Runtime Version:4.0.30319.269
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace DFM.Tests.D_Robot
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.6.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("b. Run the schedules for an user")]
    public partial class B_RunTheSchedulesForAnUserFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "b.RunSchedule.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "b. Run the schedules for an user", "", GenerationTargetLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            this.FeatureBackground();
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void FeatureBackground()
        {
#line 3
#line 4
 testRunner.Given("I have an user");
#line 5
 testRunner.And("I have two accounts");
#line 6
 testRunner.And("I have a category");
#line 7
 testRunner.And("I run the scheduler to cleanup older tests");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("01. Run with unlogged user (E)")]
        public virtual void _01_RunWithUnloggedUserE()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("01. Run with unlogged user (E)", ((string[])(null)));
#line 9
this.ScenarioSetup(scenarioInfo);
#line 10
 testRunner.Given("I have no logged user (logoff)");
#line 11
 testRunner.When("I try to run the scheduler");
#line 12
 testRunner.Then("I will receive this error: Unauthorized");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("91. Run with bounded schedule (S)")]
        public virtual void _91_RunWithBoundedScheduleS()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("91. Run with bounded schedule (S)", ((string[])(null)));
#line 15
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value"});
            table1.AddRow(new string[] {
                        "Move Ca91",
                        "2012-03-31",
                        "Out",
                        "10"});
#line 16
 testRunner.Given("I have this future move to create", ((string)(null)), table1);
#line 19
 testRunner.And("it has no Details");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Times",
                        "Boundless",
                        "Frequency",
                        "ShowInstallment"});
            table2.AddRow(new string[] {
                        "1",
                        "False",
                        "Monthly",
                        "False"});
#line 20
 testRunner.And("the move has this schedule", ((string)(null)), table2);
#line 23
 testRunner.And("it has a Category");
#line 24
 testRunner.And("it has an Account Out");
#line 25
 testRunner.And("it has no Account In");
#line 26
 testRunner.And("I save the schedule");
#line 27
 testRunner.When("I try to run the scheduler");
#line 28
 testRunner.Then("the accountOut value will change in -10");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("92. Run with boundless schedule (S)")]
        public virtual void _92_RunWithBoundlessScheduleS()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("92. Run with boundless schedule (S)", ((string[])(null)));
#line 30
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value"});
            table3.AddRow(new string[] {
                        "Move Ca92",
                        "",
                        "Out",
                        "10"});
#line 31
 testRunner.Given("I have this future move to create", ((string)(null)), table3);
#line 34
 testRunner.And("its Date is 3 months ago");
#line 35
 testRunner.And("it has no Details");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Times",
                        "Boundless",
                        "Frequency",
                        "ShowInstallment"});
            table4.AddRow(new string[] {
                        "",
                        "True",
                        "Monthly",
                        "False"});
#line 36
 testRunner.And("the move has this schedule", ((string)(null)), table4);
#line 39
 testRunner.And("it has a Category");
#line 40
 testRunner.And("it has an Account Out");
#line 41
 testRunner.And("it has no Account In");
#line 42
 testRunner.And("I save the schedule");
#line 43
 testRunner.When("I try to run the scheduler");
#line 44
 testRunner.Then("the accountOut value will change in -40");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("93. Run schedule that will finish (S)")]
        public virtual void _93_RunScheduleThatWillFinishS()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("93. Run schedule that will finish (S)", ((string[])(null)));
#line 46
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value"});
            table5.AddRow(new string[] {
                        "Move Ca93",
                        "",
                        "Out",
                        "10"});
#line 47
 testRunner.Given("I have this future move to create", ((string)(null)), table5);
#line 50
 testRunner.And("its Date is 5 days ago");
#line 51
 testRunner.And("it has no Details");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Times",
                        "Boundless",
                        "Frequency",
                        "ShowInstallment"});
            table6.AddRow(new string[] {
                        "3",
                        "False",
                        "Daily",
                        "False"});
#line 52
 testRunner.And("the move has this schedule", ((string)(null)), table6);
#line 55
 testRunner.And("it has a Category");
#line 56
 testRunner.And("it has an Account Out");
#line 57
 testRunner.And("it has no Account In");
#line 58
 testRunner.And("I save the schedule");
#line 59
 testRunner.When("I try to run the scheduler");
#line 60
 testRunner.Then("the accountOut value will change in -30");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("94. Run schedule that wont finish (S)")]
        public virtual void _94_RunScheduleThatWontFinishS()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("94. Run schedule that wont finish (S)", ((string[])(null)));
#line 62
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value"});
            table7.AddRow(new string[] {
                        "Move Ca94",
                        "",
                        "Out",
                        "10"});
#line 63
 testRunner.Given("I have this future move to create", ((string)(null)), table7);
#line 66
 testRunner.And("its Date is 5 days ago");
#line 67
 testRunner.And("it has no Details");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Times",
                        "Boundless",
                        "Frequency",
                        "ShowInstallment"});
            table8.AddRow(new string[] {
                        "7",
                        "False",
                        "Daily",
                        "False"});
#line 68
 testRunner.And("the move has this schedule", ((string)(null)), table8);
#line 71
 testRunner.And("it has a Category");
#line 72
 testRunner.And("it has an Account Out");
#line 73
 testRunner.And("it has no Account In");
#line 74
 testRunner.And("I save the schedule");
#line 75
 testRunner.When("I try to run the scheduler");
#line 76
 testRunner.Then("the accountOut value will change in -60");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("95. Run with daily schedule (S)")]
        public virtual void _95_RunWithDailyScheduleS()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("95. Run with daily schedule (S)", ((string[])(null)));
#line 78
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value"});
            table9.AddRow(new string[] {
                        "Move Ca95",
                        "",
                        "Out",
                        "10"});
#line 79
 testRunner.Given("I have this future move to create", ((string)(null)), table9);
#line 82
 testRunner.And("its Date is 20 days ago");
#line 83
 testRunner.And("it has no Details");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "Times",
                        "Boundless",
                        "Frequency",
                        "ShowInstallment"});
            table10.AddRow(new string[] {
                        "10",
                        "False",
                        "Daily",
                        "False"});
#line 84
 testRunner.And("the move has this schedule", ((string)(null)), table10);
#line 87
 testRunner.And("it has a Category");
#line 88
 testRunner.And("it has an Account Out");
#line 89
 testRunner.And("it has no Account In");
#line 90
 testRunner.And("I save the schedule");
#line 91
 testRunner.When("I try to run the scheduler");
#line 92
 testRunner.Then("the accountOut value will change in -100");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("96. Run with monthly schedule (S)")]
        public virtual void _96_RunWithMonthlyScheduleS()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("96. Run with monthly schedule (S)", ((string[])(null)));
#line 94
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value"});
            table11.AddRow(new string[] {
                        "Move Ca96",
                        "",
                        "Out",
                        "10"});
#line 95
 testRunner.Given("I have this future move to create", ((string)(null)), table11);
#line 98
 testRunner.And("its Date is 7 months ago");
#line 99
 testRunner.And("it has no Details");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "Times",
                        "Boundless",
                        "Frequency",
                        "ShowInstallment"});
            table12.AddRow(new string[] {
                        "6",
                        "False",
                        "Monthly",
                        "False"});
#line 100
 testRunner.And("the move has this schedule", ((string)(null)), table12);
#line 103
 testRunner.And("it has a Category");
#line 104
 testRunner.And("it has an Account Out");
#line 105
 testRunner.And("it has no Account In");
#line 106
 testRunner.And("I save the schedule");
#line 107
 testRunner.When("I try to run the scheduler");
#line 108
 testRunner.Then("the accountOut value will change in -60");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("97. Run with yearly schedule (S)")]
        public virtual void _97_RunWithYearlyScheduleS()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("97. Run with yearly schedule (S)", ((string[])(null)));
#line 110
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value"});
            table13.AddRow(new string[] {
                        "Move Ca97",
                        "",
                        "Out",
                        "10"});
#line 111
 testRunner.Given("I have this future move to create", ((string)(null)), table13);
#line 114
 testRunner.And("its Date is 2 years ago");
#line 115
 testRunner.And("it has no Details");
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "Times",
                        "Boundless",
                        "Frequency",
                        "ShowInstallment"});
            table14.AddRow(new string[] {
                        "2",
                        "False",
                        "Monthly",
                        "False"});
#line 116
 testRunner.And("the move has this schedule", ((string)(null)), table14);
#line 119
 testRunner.And("it has a Category");
#line 120
 testRunner.And("it has an Account Out");
#line 121
 testRunner.And("it has no Account In");
#line 122
 testRunner.And("I save the schedule");
#line 123
 testRunner.When("I try to run the scheduler");
#line 124
 testRunner.Then("the accountOut value will change in -20");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("98. Run with details in schedule (S)")]
        public virtual void _98_RunWithDetailsInScheduleS()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("98. Run with details in schedule (S)", ((string[])(null)));
#line 126
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value"});
            table15.AddRow(new string[] {
                        "Move Ca98",
                        "",
                        "Out",
                        ""});
#line 127
 testRunner.Given("I have this future move to create", ((string)(null)), table15);
#line 130
 testRunner.And("its Date is 10 days ago");
#line hidden
            TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Amount",
                        "Value"});
            table16.AddRow(new string[] {
                        "Detail 1",
                        "1",
                        "10"});
            table16.AddRow(new string[] {
                        "Detail 2",
                        "1",
                        "10"});
#line 131
 testRunner.And("the move has this details", ((string)(null)), table16);
#line hidden
            TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                        "Times",
                        "Boundless",
                        "Frequency",
                        "ShowInstallment"});
            table17.AddRow(new string[] {
                        "5",
                        "False",
                        "Daily",
                        "False"});
#line 135
 testRunner.And("the move has this schedule", ((string)(null)), table17);
#line 138
 testRunner.And("it has a Category");
#line 139
 testRunner.And("it has an Account Out");
#line 140
 testRunner.And("it has no Account In");
#line 141
 testRunner.And("I save the schedule");
#line 142
 testRunner.When("I try to run the scheduler");
#line 143
 testRunner.Then("the accountOut value will change in -100");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
