Feature: A. Move to CSV object

Scenario: A01. Transform move
	Given this move data
			| Guid | Description | Date       | CategoryName | Nature   | InName | OutName | Value | Conversion |
			| 1    | Move 1      | 2021-05-11 | Cat          | Transfer | In     | Out     | 10    |            |
			| 2    | Move 2      | 2021-05-10 | Cat          | Out      |        | Out     | 20    |            |
			| 3    | Move 3      | 2021-05-09 | Cat          | In       | In     |         | 30    |            |
			| 4    | Move 4      | 2021-05-08 |              | Transfer | In     | Out     | 40    |            |
			| 5    | Move 5      | 2021-05-07 |              | Transfer | In     | Out     | 40    | 200        |
	When convert to csv
	Then the csv will have these lines
			| Description | Date       | Category | Nature   | In | Out | Value | Conversion | Description1 | Amount1 | Value1 | Conversion1 | Description2 | Amount2 | Value2 | Conversion2 | Description3 | Amount3 | Value3 | Conversion3 | Description4 | Amount4 | Value4 | Conversion4 | Description5 | Amount5 | Value5 | Conversion5 | Description6 | Amount6 | Value6 | Conversion6 | Description7 | Amount7 | Value7 | Conversion7 | Description8 | Amount8 | Value8 | Conversion8 | Description9 | Amount9 | Value9 | Conversion9 | Description10 | Amount10 | Value10 | Conversion10 | Description11 | Amount11 | Value11 | Conversion11 | Description12 | Amount12 | Value12 | Conversion12 | Description13 | Amount13 | Value13 | Conversion13 | Description14 | Amount14 | Value14 | Conversion14 | Description15 | Amount15 | Value15 | Conversion15 | Description16 | Amount16 | Value16 | Conversion16 | Description17 | Amount17 | Value17 | Conversion17 | Description18 | Amount18 | Value18 | Conversion18 | Description19 | Amount19 | Value19 | Conversion19 | Description20 | Amount20 | Value20 | Conversion20 | Description21 | Amount21 | Value21 | Conversion21 | Description22 | Amount22 | Value22 | Conversion22 | Description23 | Amount23 | Value23 | Conversion23 | Description24 | Amount24 | Value24 | Conversion24 | Description25 | Amount25 | Value25 | Conversion25 | Description26 | Amount26 | Value26 | Conversion26 | Description27 | Amount27 | Value27 | Conversion27 | Description28 | Amount28 | Value28 | Conversion28 | Description29 | Amount29 | Value29 | Conversion29 | Description30 | Amount30 | Value30 | Conversion30 |
			| Move 5      | 2021-05-07 |          | Transfer | In | Out | 40.00 | 200.00     |              |         |        |             |              |         |        |             |              |         |        |             |              |         |        |             |              |         |        |             |              |         |        |             |              |         |        |             |              |         |        |             |              |         |        |             |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |
			| Move 4      | 2021-05-08 |          | Transfer | In | Out | 40.00 |            |              |         |        |             |              |         |        |             |              |         |        |             |              |         |        |             |              |         |        |             |              |         |        |             |              |         |        |             |              |         |        |             |              |         |        |             |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |
			| Move 3      | 2021-05-09 | Cat      | In       | In |     | 30.00 |            |              |         |        |             |              |         |        |             |              |         |        |             |              |         |        |             |              |         |        |             |              |         |        |             |              |         |        |             |              |         |        |             |              |         |        |             |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |
			| Move 2      | 2021-05-10 | Cat      | Out      |    | Out | 20.00 |            |              |         |        |             |              |         |        |             |              |         |        |             |              |         |        |             |              |         |        |             |              |         |        |             |              |         |        |             |              |         |        |             |              |         |        |             |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |
			| Move 1      | 2021-05-11 | Cat      | Transfer | In | Out | 10.00 |            |              |         |        |             |              |         |        |             |              |         |        |             |              |         |        |             |              |         |        |             |              |         |        |             |              |         |        |             |              |         |        |             |              |         |        |             |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |

Scenario: A02. Transform move with detail
	Given this move data
			| Guid | Description | Date       | CategoryName | Nature   | InName | OutName |
			| 5    | Move 5      | 2021-05-11 | Cat          | Transfer | In     | Out     |
			| 6    | Move 6      | 2021-05-10 | Cat          | Out      |        | Out     |
			| 7    | Move 7      | 2021-05-09 | Cat          | In       | In     |         |
			| 8    | Move 8      | 2021-05-08 | Cat          | Transfer | In     | Out     |
		And this detail data
			| Parent | Description | Amount | Value | Conversion |
			| Move 5 | Detail 4    | 4      | 0.40  |            |
			| Move 6 | Detail 5    | 5      | 0.50  |            |
			| Move 6 | Detail 6    | 6      | 0.60  |            |
			| Move 7 | Detail 7    | 7      | 0.70  |            |
			| Move 7 | Detail 8    | 8      | 0.80  |            |
			| Move 7 | Detail 9    | 9      | 0.90  |            |
			| Move 8 | Detail 10   | 10     | 1.00  | 5.00       |
	When convert to csv
	Then the csv will have these lines
			| Description | Date       | Category | Nature   | In | Out | Value | Conversion | Description1 | Amount1 | Value1 | Conversion1 | Description2 | Amount2 | Value2 | Conversion2 | Description3 | Amount3 | Value3 | Conversion3 | Description4 | Amount4 | Value4 | Conversion4 | Description5 | Amount5 | Value5 | Conversion5 | Description6 | Amount6 | Value6 | Conversion6 | Description7 | Amount7 | Value7 | Conversion7 | Description8 | Amount8 | Value8 | Conversion8 | Description9 | Amount9 | Value9 | Conversion9 | Description10 | Amount10 | Value10 | Conversion10 | Description11 | Amount11 | Value11 | Conversion11 | Description12 | Amount12 | Value12 | Conversion12 | Description13 | Amount13 | Value13 | Conversion13 | Description14 | Amount14 | Value14 | Conversion14 | Description15 | Amount15 | Value15 | Conversion15 | Description16 | Amount16 | Value16 | Conversion16 | Description17 | Amount17 | Value17 | Conversion17 | Description18 | Amount18 | Value18 | Conversion18 | Description19 | Amount19 | Value19 | Conversion19 | Description20 | Amount20 | Value20 | Conversion20 | Description21 | Amount21 | Value21 | Conversion21 | Description22 | Amount22 | Value22 | Conversion22 | Description23 | Amount23 | Value23 | Conversion23 | Description24 | Amount24 | Value24 | Conversion24 | Description25 | Amount25 | Value25 | Conversion25 | Description26 | Amount26 | Value26 | Conversion26 | Description27 | Amount27 | Value27 | Conversion27 | Description28 | Amount28 | Value28 | Conversion28 | Description29 | Amount29 | Value29 | Conversion29 | Description30 | Amount30 | Value30 | Conversion30 |
			| Move 8      | 2021-05-08 | Cat      | Transfer | In | Out |       |            | Detail 10    | 10      | 1.00   | 5.00        |              |         |        |             |              |         |        |             |              |         |        |             |              |         |        |             |              |         |        |             |              |         |        |             |              |         |        |             |              |         |        |             |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |
			| Move 7      | 2021-05-09 | Cat      | In       | In |     |       |            | Detail 7     | 7       | 0.70   |             | Detail 8     | 8       | 0.80   |             | Detail 9     | 9       | 0.90   |             |              |         |        |             |              |         |        |             |              |         |        |             |              |         |        |             |              |         |        |             |              |         |        |             |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |
			| Move 6      | 2021-05-10 | Cat      | Out      |    | Out |       |            | Detail 5     | 5       | 0.50   |             | Detail 6     | 6       | 0.60   |             |              |         |        |             |              |         |        |             |              |         |        |             |              |         |        |             |              |         |        |             |              |         |        |             |              |         |        |             |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |
			| Move 5      | 2021-05-11 | Cat      | Transfer | In | Out |       |            | Detail 4     | 4       | 0.40   |             |              |         |        |             |              |         |        |             |              |         |        |             |              |         |        |             |              |         |        |             |              |         |        |             |              |         |        |             |              |         |        |             |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |               |          |         |              |
