services:
  mysql:
    image: mysql
    container_name: dfm-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ~/mysql/data:/var/lib/mysql
      - ./all.sql:/docker-entrypoint-initdb.d/all.sql
    ports:
      - 3306:3306
