services:
  mysql:
    image: mysql
    hostname: dfm-mysql
    container_name: dfm-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./data:/var/lib/mysql
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5

  cloud_watch:
    image: localstack/localstack
    container_name: aws-cloud-watch
    hostname: aws-cloud-watch
    ports:
      - 4566:4566
    env_file: db.env
    volumes:
      - ./localstack.sh:/etc/localstack/init/ready.d/script.sh

  migrator:
    image: darakeon/dfm-migrator
    container_name: dfm-migrator
    env_file: db.env
    volumes:
      - .:/var/db
    depends_on:
      mysql:
        condition: service_healthy
      cloud_watch:
        condition: service_healthy
