// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.6.1.0
//      SpecFlow Generator Version:1.6.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace DFM.Tests.BusinessLogic.D_Robot
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.6.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("a. Creation of schedules")]
    public partial class A_CreationOfSchedulesFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "a.SaveSchedule.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "a. Creation of schedules", "", GenerationTargetLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            this.FeatureBackground();
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void FeatureBackground()
        {
#line 3
#line 4
 testRunner.Given("I have an active user");
#line 5
 testRunner.And("I enable Categories use");
#line 6
 testRunner.And("I have two accounts");
#line 7
 testRunner.And("I have a category");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("01. Save without Description (E)")]
        public virtual void _01_SaveWithoutDescriptionE()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("01. Save without Description (E)", ((string[])(null)));
#line 9
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value",
                        "Times",
                        "Boundless",
                        "Frequency",
                        "ShowInstallment"});
            table1.AddRow(new string[] {
                        "",
                        "2012-03-31",
                        "Out",
                        "10",
                        "10",
                        "False",
                        "Monthly",
                        "False"});
#line 10
 testRunner.Given("I have this schedule to create", ((string)(null)), table1);
#line 13
 testRunner.And("it has no Details");
#line 14
 testRunner.And("it has a Category");
#line 15
 testRunner.And("it has an Account Out");
#line 16
 testRunner.And("it has no Account In");
#line 17
 testRunner.When("I try to save the schedule");
#line 18
 testRunner.Then("I will receive this core error: MoveDescriptionRequired");
#line 19
 testRunner.And("the schedule will not be saved");
#line 20
 testRunner.And("the accountOut value will not change");
#line 21
 testRunner.And("the month-category-accountOut value will not change");
#line 22
 testRunner.And("the year-category-accountOut value will not change");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("02. Save without Date (E)")]
        public virtual void _02_SaveWithoutDateE()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("02. Save without Date (E)", ((string[])(null)));
#line 24
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value",
                        "Times",
                        "Boundless",
                        "Frequency",
                        "ShowInstallment"});
            table2.AddRow(new string[] {
                        "Move Da02",
                        "",
                        "Out",
                        "10",
                        "10",
                        "False",
                        "Monthly",
                        "False"});
#line 25
 testRunner.Given("I have this schedule to create", ((string)(null)), table2);
#line 28
 testRunner.And("it has no Details");
#line 29
 testRunner.And("it has a Category");
#line 30
 testRunner.And("it has an Account Out");
#line 31
 testRunner.And("it has no Account In");
#line 32
 testRunner.When("I try to save the schedule");
#line 33
 testRunner.Then("I will receive this core error: MoveDateRequired");
#line 34
 testRunner.And("the schedule will not be saved");
#line 35
 testRunner.And("the accountOut value will not change");
#line 36
 testRunner.And("the month-category-accountOut value will not change");
#line 37
 testRunner.And("the year-category-accountOut value will not change");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("03. Save without Category (E)")]
        public virtual void _03_SaveWithoutCategoryE()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("03. Save without Category (E)", ((string[])(null)));
#line 39
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value",
                        "Times",
                        "Boundless",
                        "Frequency",
                        "ShowInstallment"});
            table3.AddRow(new string[] {
                        "Move Da03",
                        "2012-03-31",
                        "Out",
                        "10",
                        "10",
                        "False",
                        "Monthly",
                        "False"});
#line 40
 testRunner.Given("I have this schedule to create", ((string)(null)), table3);
#line 43
 testRunner.And("it has no Details");
#line 44
 testRunner.And("it has no Category");
#line 45
 testRunner.And("it has an Account Out");
#line 46
 testRunner.And("it has no Account In");
#line 47
 testRunner.When("I try to save the schedule");
#line 48
 testRunner.Then("I will receive this core error: InvalidCategory");
#line 49
 testRunner.And("the schedule will not be saved");
#line 50
 testRunner.And("the accountOut value will not change");
#line 51
 testRunner.And("the month-category-accountOut value will not change");
#line 52
 testRunner.And("the year-category-accountOut value will not change");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("04. Save with unknown Category (E)")]
        public virtual void _04_SaveWithUnknownCategoryE()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("04. Save with unknown Category (E)", ((string[])(null)));
#line 54
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value",
                        "Times",
                        "Boundless",
                        "Frequency",
                        "ShowInstallment"});
            table4.AddRow(new string[] {
                        "Move Da04",
                        "2012-03-31",
                        "Out",
                        "10",
                        "10",
                        "False",
                        "Monthly",
                        "False"});
#line 55
 testRunner.Given("I have this schedule to create", ((string)(null)), table4);
#line 58
 testRunner.And("it has no Details");
#line 59
 testRunner.And("it has an unknown Category");
#line 60
 testRunner.And("it has an Account Out");
#line 61
 testRunner.And("it has no Account In");
#line 62
 testRunner.When("I try to save the schedule");
#line 63
 testRunner.Then("I will receive this core error: InvalidCategory");
#line 64
 testRunner.And("the schedule will not be saved");
#line 65
 testRunner.And("the accountOut value will not change");
#line 66
 testRunner.And("the month-category-accountOut value will not change");
#line 67
 testRunner.And("the year-category-accountOut value will not change");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("05. Save with Description too large (E)")]
        public virtual void _05_SaveWithDescriptionTooLargeE()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("05. Save with Description too large (E)", ((string[])(null)));
#line 69
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value",
                        "Times",
                        "Boundless",
                        "Frequency",
                        "ShowInstallment"});
            table5.AddRow(new string[] {
                        "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxy",
                        "2012-03-31",
                        "Out",
                        "10",
                        "10",
                        "False",
                        "Monthly",
                        "False"});
#line 70
 testRunner.Given("I have this schedule to create", ((string)(null)), table5);
#line 73
 testRunner.And("it has no Details");
#line 74
 testRunner.And("it has a Category");
#line 75
 testRunner.And("it has an Account Out");
#line 76
 testRunner.And("it has no Account In");
#line 77
 testRunner.When("I try to save the schedule");
#line 78
 testRunner.Then("I will receive this core error: TooLargeData");
#line 79
 testRunner.And("the schedule will not be saved");
#line 80
 testRunner.And("the accountOut value will not change");
#line 81
 testRunner.And("the month-category-accountOut value will not change");
#line 82
 testRunner.And("the year-category-accountOut value will not change");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("11. Save with (Nature: Out) (AccountOut:No) (AccountIn:No) (E)")]
        public virtual void _11_SaveWithNatureOutAccountOutNoAccountInNoE()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("11. Save with (Nature: Out) (AccountOut:No) (AccountIn:No) (E)", ((string[])(null)));
#line 86
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value",
                        "Times",
                        "Boundless",
                        "Frequency",
                        "ShowInstallment"});
            table6.AddRow(new string[] {
                        "Move Da11",
                        "2012-03-31",
                        "Out",
                        "10",
                        "10",
                        "False",
                        "Monthly",
                        "False"});
#line 87
 testRunner.Given("I have this schedule to create", ((string)(null)), table6);
#line 90
 testRunner.And("it has no Details");
#line 91
 testRunner.And("it has a Category");
#line 92
 testRunner.And("it has no Account Out");
#line 93
 testRunner.And("it has no Account In");
#line 94
 testRunner.When("I try to save the schedule");
#line 95
 testRunner.Then("I will receive this core error: OutMoveWrong");
#line 96
 testRunner.And("the schedule will not be saved");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("12. Save with (Nature: Out) (AccountOut:Yes) (AccountIn:Yes) (E)")]
        public virtual void _12_SaveWithNatureOutAccountOutYesAccountInYesE()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("12. Save with (Nature: Out) (AccountOut:Yes) (AccountIn:Yes) (E)", ((string[])(null)));
#line 98
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value",
                        "Times",
                        "Boundless",
                        "Frequency",
                        "ShowInstallment"});
            table7.AddRow(new string[] {
                        "Move Da12",
                        "2012-03-31",
                        "Out",
                        "10",
                        "10",
                        "False",
                        "Monthly",
                        "False"});
#line 99
 testRunner.Given("I have this schedule to create", ((string)(null)), table7);
#line 102
 testRunner.And("it has no Details");
#line 103
 testRunner.And("it has a Category");
#line 104
 testRunner.And("it has an Account Out");
#line 105
 testRunner.And("it has an Account In");
#line 106
 testRunner.When("I try to save the schedule");
#line 107
 testRunner.Then("I will receive this core error: OutMoveWrong");
#line 108
 testRunner.And("the schedule will not be saved");
#line 109
 testRunner.And("the accountOut value will not change");
#line 110
 testRunner.And("the month-category-accountOut value will not change");
#line 111
 testRunner.And("the year-category-accountOut value will not change");
#line 112
 testRunner.And("the accountIn value will not change");
#line 113
 testRunner.And("the month-category-accountIn value will not change");
#line 114
 testRunner.And("the year-category-accountIn value will not change");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("13. Save with (Nature: Out) (AccountOut:No) (AccountIn:Yes) (E)")]
        public virtual void _13_SaveWithNatureOutAccountOutNoAccountInYesE()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("13. Save with (Nature: Out) (AccountOut:No) (AccountIn:Yes) (E)", ((string[])(null)));
#line 116
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value",
                        "Times",
                        "Boundless",
                        "Frequency",
                        "ShowInstallment"});
            table8.AddRow(new string[] {
                        "Move Da13",
                        "2012-03-31",
                        "Out",
                        "10",
                        "10",
                        "False",
                        "Monthly",
                        "False"});
#line 117
 testRunner.Given("I have this schedule to create", ((string)(null)), table8);
#line 120
 testRunner.And("it has no Details");
#line 121
 testRunner.And("it has a Category");
#line 122
 testRunner.And("it has no Account Out");
#line 123
 testRunner.And("it has an Account In");
#line 124
 testRunner.When("I try to save the schedule");
#line 125
 testRunner.Then("I will receive this core error: OutMoveWrong");
#line 126
 testRunner.And("the schedule will not be saved");
#line 127
 testRunner.And("the accountIn value will not change");
#line 128
 testRunner.And("the month-category-accountIn value will not change");
#line 129
 testRunner.And("the year-category-accountIn value will not change");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("14. Save with (Nature: Out) (AccountOut:Unknown) (AccountIn:No) (E)")]
        public virtual void _14_SaveWithNatureOutAccountOutUnknownAccountInNoE()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("14. Save with (Nature: Out) (AccountOut:Unknown) (AccountIn:No) (E)", ((string[])(null)));
#line 131
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value",
                        "Times",
                        "Boundless",
                        "Frequency",
                        "ShowInstallment"});
            table9.AddRow(new string[] {
                        "Move Da14",
                        "2012-03-31",
                        "Out",
                        "10",
                        "10",
                        "False",
                        "Monthly",
                        "False"});
#line 132
 testRunner.Given("I have this schedule to create", ((string)(null)), table9);
#line 135
 testRunner.And("it has no Details");
#line 136
 testRunner.And("it has a Category");
#line 137
 testRunner.And("it has an unknown Account Out");
#line 138
 testRunner.And("it has no Account In");
#line 139
 testRunner.When("I try to save the schedule");
#line 140
 testRunner.Then("I will receive this core error: InvalidAccount");
#line 141
 testRunner.And("the schedule will not be saved");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("21. Save with (Nature: In) (AccountOut:No) (AccountIn:No) (E)")]
        public virtual void _21_SaveWithNatureInAccountOutNoAccountInNoE()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("21. Save with (Nature: In) (AccountOut:No) (AccountIn:No) (E)", ((string[])(null)));
#line 145
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value",
                        "Times",
                        "Boundless",
                        "Frequency",
                        "ShowInstallment"});
            table10.AddRow(new string[] {
                        "Move Da21",
                        "2012-03-31",
                        "In",
                        "10",
                        "10",
                        "False",
                        "Monthly",
                        "False"});
#line 146
 testRunner.Given("I have this schedule to create", ((string)(null)), table10);
#line 149
 testRunner.And("it has no Details");
#line 150
 testRunner.And("it has a Category");
#line 151
 testRunner.And("it has no Account Out");
#line 152
 testRunner.And("it has no Account In");
#line 153
 testRunner.When("I try to save the schedule");
#line 154
 testRunner.Then("I will receive this core error: InMoveWrong");
#line 155
 testRunner.And("the schedule will not be saved");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("22. Save with (Nature: In) (AccountOut:Yes) (AccountIn:Yes) (E)")]
        public virtual void _22_SaveWithNatureInAccountOutYesAccountInYesE()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("22. Save with (Nature: In) (AccountOut:Yes) (AccountIn:Yes) (E)", ((string[])(null)));
#line 157
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value",
                        "Times",
                        "Boundless",
                        "Frequency",
                        "ShowInstallment"});
            table11.AddRow(new string[] {
                        "Move Da22",
                        "2012-03-31",
                        "In",
                        "10",
                        "10",
                        "False",
                        "Monthly",
                        "False"});
#line 158
 testRunner.Given("I have this schedule to create", ((string)(null)), table11);
#line 161
 testRunner.And("it has no Details");
#line 162
 testRunner.And("it has a Category");
#line 163
 testRunner.And("it has an Account Out");
#line 164
 testRunner.And("it has an Account In");
#line 165
 testRunner.When("I try to save the schedule");
#line 166
 testRunner.Then("I will receive this core error: InMoveWrong");
#line 167
 testRunner.And("the schedule will not be saved");
#line 168
 testRunner.And("the accountOut value will not change");
#line 169
 testRunner.And("the month-category-accountOut value will not change");
#line 170
 testRunner.And("the year-category-accountOut value will not change");
#line 171
 testRunner.And("the accountIn value will not change");
#line 172
 testRunner.And("the month-category-accountIn value will not change");
#line 173
 testRunner.And("the year-category-accountIn value will not change");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("23. Save with (Nature: In) (AccountOut:Yes) (AccountIn:No) (E)")]
        public virtual void _23_SaveWithNatureInAccountOutYesAccountInNoE()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("23. Save with (Nature: In) (AccountOut:Yes) (AccountIn:No) (E)", ((string[])(null)));
#line 175
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value",
                        "Times",
                        "Boundless",
                        "Frequency",
                        "ShowInstallment"});
            table12.AddRow(new string[] {
                        "Move Da23",
                        "2012-03-31",
                        "In",
                        "10",
                        "10",
                        "False",
                        "Monthly",
                        "False"});
#line 176
 testRunner.Given("I have this schedule to create", ((string)(null)), table12);
#line 179
 testRunner.And("it has no Details");
#line 180
 testRunner.And("it has a Category");
#line 181
 testRunner.And("it has an Account Out");
#line 182
 testRunner.And("it has no Account In");
#line 183
 testRunner.When("I try to save the schedule");
#line 184
 testRunner.Then("I will receive this core error: InMoveWrong");
#line 185
 testRunner.And("the schedule will not be saved");
#line 186
 testRunner.And("the accountOut value will not change");
#line 187
 testRunner.And("the month-category-accountOut value will not change");
#line 188
 testRunner.And("the year-category-accountOut value will not change");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("24. Save with (Nature: In) (AccountOut:No) (AccountIn:Unknown) (E)")]
        public virtual void _24_SaveWithNatureInAccountOutNoAccountInUnknownE()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("24. Save with (Nature: In) (AccountOut:No) (AccountIn:Unknown) (E)", ((string[])(null)));
#line 190
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value",
                        "Times",
                        "Boundless",
                        "Frequency",
                        "ShowInstallment"});
            table13.AddRow(new string[] {
                        "Move Da24",
                        "2012-03-31",
                        "In",
                        "10",
                        "10",
                        "False",
                        "Monthly",
                        "False"});
#line 191
 testRunner.Given("I have this schedule to create", ((string)(null)), table13);
#line 194
 testRunner.And("it has no Details");
#line 195
 testRunner.And("it has a Category");
#line 196
 testRunner.And("it has no Account Out");
#line 197
 testRunner.And("it has an unknown Account In");
#line 198
 testRunner.When("I try to save the schedule");
#line 199
 testRunner.Then("I will receive this core error: InvalidAccount");
#line 200
 testRunner.And("the schedule will not be saved");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("31. Save with (Nature: Transfer) (AccountOut:No) (AccountIn:No) (E)")]
        public virtual void _31_SaveWithNatureTransferAccountOutNoAccountInNoE()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("31. Save with (Nature: Transfer) (AccountOut:No) (AccountIn:No) (E)", ((string[])(null)));
#line 204
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value",
                        "Times",
                        "Boundless",
                        "Frequency",
                        "ShowInstallment"});
            table14.AddRow(new string[] {
                        "Move Da31",
                        "2012-03-31",
                        "Transfer",
                        "10",
                        "10",
                        "False",
                        "Monthly",
                        "False"});
#line 205
 testRunner.Given("I have this schedule to create", ((string)(null)), table14);
#line 208
 testRunner.And("it has no Details");
#line 209
 testRunner.And("it has a Category");
#line 210
 testRunner.And("it has no Account Out");
#line 211
 testRunner.And("it has no Account In");
#line 212
 testRunner.When("I try to save the schedule");
#line 213
 testRunner.Then("I will receive this core error: TransferMoveWrong");
#line 214
 testRunner.And("the schedule will not be saved");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("32. Save with (Nature: Transfer) (AccountOut:No) (AccountIn:Yes) (E)")]
        public virtual void _32_SaveWithNatureTransferAccountOutNoAccountInYesE()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("32. Save with (Nature: Transfer) (AccountOut:No) (AccountIn:Yes) (E)", ((string[])(null)));
#line 216
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value",
                        "Times",
                        "Boundless",
                        "Frequency",
                        "ShowInstallment"});
            table15.AddRow(new string[] {
                        "Move Da32",
                        "2012-03-31",
                        "Transfer",
                        "10",
                        "10",
                        "False",
                        "Monthly",
                        "False"});
#line 217
 testRunner.Given("I have this schedule to create", ((string)(null)), table15);
#line 220
 testRunner.And("it has no Details");
#line 221
 testRunner.And("it has a Category");
#line 222
 testRunner.And("it has no Account Out");
#line 223
 testRunner.And("it has an Account In");
#line 224
 testRunner.When("I try to save the schedule");
#line 225
 testRunner.Then("I will receive this core error: TransferMoveWrong");
#line 226
 testRunner.And("the schedule will not be saved");
#line 227
 testRunner.And("the accountIn value will not change");
#line 228
 testRunner.And("the month-category-accountIn value will not change");
#line 229
 testRunner.And("the year-category-accountIn value will not change");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("33. Save with (Nature: Transfer) (AccountOut:Yes) (AccountIn:No) (E)")]
        public virtual void _33_SaveWithNatureTransferAccountOutYesAccountInNoE()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("33. Save with (Nature: Transfer) (AccountOut:Yes) (AccountIn:No) (E)", ((string[])(null)));
#line 231
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value",
                        "Times",
                        "Boundless",
                        "Frequency",
                        "ShowInstallment"});
            table16.AddRow(new string[] {
                        "Move Da33",
                        "2012-03-31",
                        "Transfer",
                        "10",
                        "10",
                        "False",
                        "Monthly",
                        "False"});
#line 232
 testRunner.Given("I have this schedule to create", ((string)(null)), table16);
#line 235
 testRunner.And("it has no Details");
#line 236
 testRunner.And("it has a Category");
#line 237
 testRunner.And("it has an Account Out");
#line 238
 testRunner.And("it has no Account In");
#line 239
 testRunner.When("I try to save the schedule");
#line 240
 testRunner.Then("I will receive this core error: TransferMoveWrong");
#line 241
 testRunner.And("the schedule will not be saved");
#line 242
 testRunner.And("the accountOut value will not change");
#line 243
 testRunner.And("the month-category-accountOut value will not change");
#line 244
 testRunner.And("the year-category-accountOut value will not change");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("34. Save with (Nature: Transfer) (AccountOut:Yes) (AccountIn:Unknown) (E)")]
        public virtual void _34_SaveWithNatureTransferAccountOutYesAccountInUnknownE()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("34. Save with (Nature: Transfer) (AccountOut:Yes) (AccountIn:Unknown) (E)", ((string[])(null)));
#line 246
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value",
                        "Times",
                        "Boundless",
                        "Frequency",
                        "ShowInstallment"});
            table17.AddRow(new string[] {
                        "Move Da34",
                        "2012-03-31",
                        "Transfer",
                        "10",
                        "10",
                        "False",
                        "Monthly",
                        "False"});
#line 247
 testRunner.Given("I have this schedule to create", ((string)(null)), table17);
#line 250
 testRunner.And("it has no Details");
#line 251
 testRunner.And("it has a Category");
#line 252
 testRunner.And("it has an Account Out");
#line 253
 testRunner.And("it has an unknown Account In");
#line 254
 testRunner.When("I try to save the schedule");
#line 255
 testRunner.Then("I will receive this core error: InvalidAccount");
#line 256
 testRunner.And("the schedule will not be saved");
#line 257
 testRunner.And("the accountOut value will not change");
#line 258
 testRunner.And("the month-category-accountOut value will not change");
#line 259
 testRunner.And("the year-category-accountOut value will not change");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("35. Save with (Nature: Transfer) (AccountOut:Unknown) (AccountIn:Yes) (E)")]
        public virtual void _35_SaveWithNatureTransferAccountOutUnknownAccountInYesE()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("35. Save with (Nature: Transfer) (AccountOut:Unknown) (AccountIn:Yes) (E)", ((string[])(null)));
#line 261
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value",
                        "Times",
                        "Boundless",
                        "Frequency",
                        "ShowInstallment"});
            table18.AddRow(new string[] {
                        "Move Da35",
                        "2012-03-31",
                        "Transfer",
                        "10",
                        "10",
                        "False",
                        "Monthly",
                        "False"});
#line 262
 testRunner.Given("I have this schedule to create", ((string)(null)), table18);
#line 265
 testRunner.And("it has no Details");
#line 266
 testRunner.And("it has a Category");
#line 267
 testRunner.And("it has an unknown Account Out");
#line 268
 testRunner.And("it has an Account In");
#line 269
 testRunner.When("I try to save the schedule");
#line 270
 testRunner.Then("I will receive this core error: InvalidAccount");
#line 271
 testRunner.And("the schedule will not be saved");
#line 272
 testRunner.And("the accountIn value will not change");
#line 273
 testRunner.And("the month-category-accountIn value will not change");
#line 274
 testRunner.And("the year-category-accountIn value will not change");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("36. Save with (Nature: Transfer) (AccountOut:Yes) (AccountIn:Equal to Out) (E)")]
        public virtual void _36_SaveWithNatureTransferAccountOutYesAccountInEqualToOutE()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("36. Save with (Nature: Transfer) (AccountOut:Yes) (AccountIn:Equal to Out) (E)", ((string[])(null)));
#line 276
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value",
                        "Times",
                        "Boundless",
                        "Frequency",
                        "ShowInstallment"});
            table19.AddRow(new string[] {
                        "Move Da36",
                        "2012-03-31",
                        "Transfer",
                        "10",
                        "10",
                        "False",
                        "Monthly",
                        "False"});
#line 277
 testRunner.Given("I have this schedule to create", ((string)(null)), table19);
#line 280
 testRunner.And("it has no Details");
#line 281
 testRunner.And("it has a Category");
#line 282
 testRunner.And("it has an Account Out");
#line 283
 testRunner.And("it has an Account In equal to Out");
#line 284
 testRunner.When("I try to save the schedule");
#line 285
 testRunner.Then("I will receive this core error: MoveCircularTransfer");
#line 286
 testRunner.And("the schedule will not be saved");
#line 287
 testRunner.And("the accountOut value will not change");
#line 288
 testRunner.And("the month-category-accountOut value will not change");
#line 289
 testRunner.And("the year-category-accountOut value will not change");
#line 290
 testRunner.And("the accountIn value will not change");
#line 291
 testRunner.And("the month-category-accountIn value will not change");
#line 292
 testRunner.And("the year-category-accountIn value will not change");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("41. Save without Value or Details (E)")]
        public virtual void _41_SaveWithoutValueOrDetailsE()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("41. Save without Value or Details (E)", ((string[])(null)));
#line 296
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value",
                        "Times",
                        "Boundless",
                        "Frequency",
                        "ShowInstallment"});
            table20.AddRow(new string[] {
                        "Move Da41",
                        "2012-03-31",
                        "Out",
                        "",
                        "10",
                        "False",
                        "Monthly",
                        "False"});
#line 297
 testRunner.Given("I have this schedule to create", ((string)(null)), table20);
#line 300
 testRunner.And("it has no Details");
#line 301
 testRunner.And("it has a Category");
#line 302
 testRunner.And("it has an Account Out");
#line 303
 testRunner.And("it has no Account In");
#line 304
 testRunner.When("I try to save the schedule");
#line 305
 testRunner.Then("I will receive this core error: MoveValueOrDetailRequired");
#line 306
 testRunner.And("the schedule will not be saved");
#line 307
 testRunner.And("the accountOut value will not change");
#line 308
 testRunner.And("the month-category-accountOut value will not change");
#line 309
 testRunner.And("the year-category-accountOut value will not change");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("42. Save with Value zero and no Details (E)")]
        public virtual void _42_SaveWithValueZeroAndNoDetailsE()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("42. Save with Value zero and no Details (E)", ((string[])(null)));
#line 311
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value",
                        "Times",
                        "Boundless",
                        "Frequency",
                        "ShowInstallment"});
            table21.AddRow(new string[] {
                        "Move Da42",
                        "2012-03-31",
                        "Out",
                        "0",
                        "10",
                        "False",
                        "Monthly",
                        "False"});
#line 312
 testRunner.Given("I have this schedule to create", ((string)(null)), table21);
#line 315
 testRunner.And("it has no Details");
#line 316
 testRunner.And("it has a Category");
#line 317
 testRunner.And("it has an Account Out");
#line 318
 testRunner.And("it has no Account In");
#line 319
 testRunner.When("I try to save the schedule");
#line 320
 testRunner.Then("I will receive this core error: MoveValueOrDetailRequired");
#line 321
 testRunner.And("the schedule will not be saved");
#line 322
 testRunner.And("the accountOut value will not change");
#line 323
 testRunner.And("the month-category-accountOut value will not change");
#line 324
 testRunner.And("the year-category-accountOut value will not change");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("43. Save without value and without Description in Detail (E)")]
        public virtual void _43_SaveWithoutValueAndWithoutDescriptionInDetailE()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("43. Save without value and without Description in Detail (E)", ((string[])(null)));
#line 326
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value",
                        "Times",
                        "Boundless",
                        "Frequency",
                        "ShowInstallment"});
            table22.AddRow(new string[] {
                        "Move Da43",
                        "2012-03-31",
                        "Out",
                        "",
                        "10",
                        "False",
                        "Monthly",
                        "False"});
#line 327
 testRunner.Given("I have this schedule to create", ((string)(null)), table22);
#line hidden
            TechTalk.SpecFlow.Table table23 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Amount",
                        "Value"});
            table23.AddRow(new string[] {
                        "",
                        "1",
                        "10"});
            table23.AddRow(new string[] {
                        "Detail 2",
                        "1",
                        "10"});
#line 330
 testRunner.And("the move has this details", ((string)(null)), table23);
#line 334
 testRunner.And("it has a Category");
#line 335
 testRunner.And("it has an Account Out");
#line 336
 testRunner.And("it has no Account In");
#line 337
 testRunner.When("I try to save the schedule");
#line 338
 testRunner.Then("I will receive this core error: MoveDetailDescriptionRequired");
#line 339
 testRunner.And("the schedule will not be saved");
#line 340
 testRunner.And("the accountOut value will not change");
#line 341
 testRunner.And("the month-category-accountOut value will not change");
#line 342
 testRunner.And("the year-category-accountOut value will not change");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("44. Save without value and with Amount zero in Detail (E)")]
        public virtual void _44_SaveWithoutValueAndWithAmountZeroInDetailE()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("44. Save without value and with Amount zero in Detail (E)", ((string[])(null)));
#line 344
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table24 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value",
                        "Times",
                        "Boundless",
                        "Frequency",
                        "ShowInstallment"});
            table24.AddRow(new string[] {
                        "Move Da44",
                        "2012-03-31",
                        "Out",
                        "",
                        "10",
                        "False",
                        "Monthly",
                        "False"});
#line 345
 testRunner.Given("I have this schedule to create", ((string)(null)), table24);
#line hidden
            TechTalk.SpecFlow.Table table25 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Amount",
                        "Value"});
            table25.AddRow(new string[] {
                        "Detail 1",
                        "0",
                        "10"});
            table25.AddRow(new string[] {
                        "Detail 2",
                        "1",
                        "10"});
#line 348
 testRunner.And("the move has this details", ((string)(null)), table25);
#line 352
 testRunner.And("it has a Category");
#line 353
 testRunner.And("it has an Account Out");
#line 354
 testRunner.And("it has no Account In");
#line 355
 testRunner.When("I try to save the schedule");
#line 356
 testRunner.Then("I will receive this core error: MoveDetailAmountRequired");
#line 357
 testRunner.And("the schedule will not be saved");
#line 358
 testRunner.And("the accountOut value will not change");
#line 359
 testRunner.And("the month-category-accountOut value will not change");
#line 360
 testRunner.And("the year-category-accountOut value will not change");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("45. Save without value and with Value zero in Detail (E)")]
        public virtual void _45_SaveWithoutValueAndWithValueZeroInDetailE()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("45. Save without value and with Value zero in Detail (E)", ((string[])(null)));
#line 362
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table26 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value",
                        "Times",
                        "Boundless",
                        "Frequency",
                        "ShowInstallment"});
            table26.AddRow(new string[] {
                        "Move Da45",
                        "2012-03-31",
                        "Out",
                        "",
                        "10",
                        "False",
                        "Monthly",
                        "False"});
#line 363
 testRunner.Given("I have this schedule to create", ((string)(null)), table26);
#line hidden
            TechTalk.SpecFlow.Table table27 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Amount",
                        "Value"});
            table27.AddRow(new string[] {
                        "Detail 1",
                        "1",
                        "0"});
            table27.AddRow(new string[] {
                        "Detail 2",
                        "1",
                        "10"});
#line 366
 testRunner.And("the move has this details", ((string)(null)), table27);
#line 370
 testRunner.And("it has a Category");
#line 371
 testRunner.And("it has an Account Out");
#line 372
 testRunner.And("it has no Account In");
#line 373
 testRunner.When("I try to save the schedule");
#line 374
 testRunner.Then("I will receive this core error: MoveDetailValueRequired");
#line 375
 testRunner.And("the schedule will not be saved");
#line 376
 testRunner.And("the accountOut value will not change");
#line 377
 testRunner.And("the month-category-accountOut value will not change");
#line 378
 testRunner.And("the year-category-accountOut value will not change");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("46. Save with Description too large in Detail (E)")]
        public virtual void _46_SaveWithDescriptionTooLargeInDetailE()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("46. Save with Description too large in Detail (E)", ((string[])(null)));
#line 380
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table28 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value",
                        "Times",
                        "Boundless",
                        "Frequency",
                        "ShowInstallment"});
            table28.AddRow(new string[] {
                        "Move Da46",
                        "2012-03-31",
                        "Out",
                        "",
                        "10",
                        "False",
                        "Monthly",
                        "False"});
#line 381
 testRunner.Given("I have this schedule to create", ((string)(null)), table28);
#line hidden
            TechTalk.SpecFlow.Table table29 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Amount",
                        "Value"});
            table29.AddRow(new string[] {
                        "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxy",
                        "1",
                        "10"});
#line 384
 testRunner.And("the move has this details", ((string)(null)), table29);
#line 387
 testRunner.And("it has a Category");
#line 388
 testRunner.And("it has an Account Out");
#line 389
 testRunner.And("it has no Account In");
#line 390
 testRunner.When("I try to save the schedule");
#line 391
 testRunner.Then("I will receive this core error: TooLargeData");
#line 392
 testRunner.And("the schedule will not be saved");
#line 393
 testRunner.And("the accountOut value will not change");
#line 394
 testRunner.And("the month-category-accountOut value will not change");
#line 395
 testRunner.And("the year-category-accountOut value will not change");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("51. Save without Schedule (E)")]
        public virtual void _51_SaveWithoutScheduleE()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("51. Save without Schedule (E)", ((string[])(null)));
#line 399
this.ScenarioSetup(scenarioInfo);
#line 400
 testRunner.Given("I have no schedule");
#line 401
 testRunner.And("it has a Category");
#line 402
 testRunner.And("it has an Account Out");
#line 403
 testRunner.And("it has no Account In");
#line 404
 testRunner.When("I try to save the schedule");
#line 405
 testRunner.Then("I will receive this core error: ScheduleRequired");
#line 406
 testRunner.And("the schedule will not be saved");
#line 407
 testRunner.And("the accountOut value will not change");
#line 408
 testRunner.And("the month-category-accountOut value will not change");
#line 409
 testRunner.And("the year-category-accountOut value will not change");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("52. Save with Schedule Times zero and bounded (E)")]
        public virtual void _52_SaveWithScheduleTimesZeroAndBoundedE()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("52. Save with Schedule Times zero and bounded (E)", ((string[])(null)));
#line 411
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table30 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value",
                        "Times",
                        "Boundless",
                        "Frequency",
                        "ShowInstallment"});
            table30.AddRow(new string[] {
                        "Move Da52",
                        "2012-03-31",
                        "Out",
                        "10",
                        "0",
                        "False",
                        "Monthly",
                        "False"});
#line 412
 testRunner.Given("I have this schedule to create", ((string)(null)), table30);
#line 415
 testRunner.And("it has no Details");
#line 416
 testRunner.And("it has a Category");
#line 417
 testRunner.And("it has an Account Out");
#line 418
 testRunner.And("it has no Account In");
#line 419
 testRunner.When("I try to save the schedule");
#line 420
 testRunner.Then("I will receive this core error: ScheduleTimesCantBeZero");
#line 421
 testRunner.And("the schedule will not be saved");
#line 422
 testRunner.And("the accountOut value will not change");
#line 423
 testRunner.And("the month-category-accountOut value will not change");
#line 424
 testRunner.And("the year-category-accountOut value will not change");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("91. Save with info all right (Out) (S)")]
        public virtual void _91_SaveWithInfoAllRightOutS()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("91. Save with info all right (Out) (S)", ((string[])(null)));
#line 428
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table31 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value",
                        "Times",
                        "Boundless",
                        "Frequency",
                        "ShowInstallment"});
            table31.AddRow(new string[] {
                        "Move Da91",
                        "2012-03-31",
                        "Out",
                        "10",
                        "10",
                        "False",
                        "Monthly",
                        "False"});
#line 429
 testRunner.Given("I have this schedule to create", ((string)(null)), table31);
#line 432
 testRunner.And("it has no Details");
#line 433
 testRunner.And("it has a Category");
#line 434
 testRunner.And("it has an Account Out");
#line 435
 testRunner.And("it has no Account In");
#line 436
 testRunner.When("I try to save the schedule");
#line 437
 testRunner.Then("I will receive no core error");
#line 438
 testRunner.And("the schedule will be saved");
#line 439
 testRunner.And("the accountOut value will not change");
#line 440
 testRunner.And("the month-category-accountOut value will not change");
#line 441
 testRunner.And("the year-category-accountOut value will not change");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("92. Save with info all right (In) (S)")]
        public virtual void _92_SaveWithInfoAllRightInS()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("92. Save with info all right (In) (S)", ((string[])(null)));
#line 443
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table32 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value",
                        "Times",
                        "Boundless",
                        "Frequency",
                        "ShowInstallment"});
            table32.AddRow(new string[] {
                        "Move Da92",
                        "2012-03-31",
                        "In",
                        "10",
                        "10",
                        "False",
                        "Monthly",
                        "False"});
#line 444
 testRunner.Given("I have this schedule to create", ((string)(null)), table32);
#line 447
 testRunner.And("it has no Details");
#line 448
 testRunner.And("it has a Category");
#line 449
 testRunner.And("it has no Account Out");
#line 450
 testRunner.And("it has an Account In");
#line 451
 testRunner.When("I try to save the schedule");
#line 452
 testRunner.Then("I will receive no core error");
#line 453
 testRunner.And("the schedule will be saved");
#line 454
 testRunner.And("the accountIn value will not change");
#line 455
 testRunner.And("the month-category-accountIn value will not change");
#line 456
 testRunner.And("the year-category-accountIn value will not change");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("93. Save with info all right (Transfer) (S)")]
        public virtual void _93_SaveWithInfoAllRightTransferS()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("93. Save with info all right (Transfer) (S)", ((string[])(null)));
#line 458
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table33 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value",
                        "Times",
                        "Boundless",
                        "Frequency",
                        "ShowInstallment"});
            table33.AddRow(new string[] {
                        "Move Da93",
                        "2012-03-31",
                        "Transfer",
                        "10",
                        "10",
                        "False",
                        "Monthly",
                        "False"});
#line 459
 testRunner.Given("I have this schedule to create", ((string)(null)), table33);
#line 462
 testRunner.And("it has no Details");
#line 463
 testRunner.And("it has a Category");
#line 464
 testRunner.And("it has an Account Out");
#line 465
 testRunner.And("it has an Account In");
#line 466
 testRunner.When("I try to save the schedule");
#line 467
 testRunner.Then("I will receive no core error");
#line 468
 testRunner.And("the schedule will be saved");
#line 469
 testRunner.And("the accountOut value will not change");
#line 470
 testRunner.And("the month-category-accountOut value will not change");
#line 471
 testRunner.And("the year-category-accountOut value will not change");
#line 472
 testRunner.And("the accountIn value will not change");
#line 473
 testRunner.And("the month-category-accountIn value will not change");
#line 474
 testRunner.And("the year-category-accountIn value will not change");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("94. Save with info all right (value) (S)")]
        public virtual void _94_SaveWithInfoAllRightValueS()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("94. Save with info all right (value) (S)", ((string[])(null)));
#line 476
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table34 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value",
                        "Times",
                        "Boundless",
                        "Frequency",
                        "ShowInstallment"});
            table34.AddRow(new string[] {
                        "Move Da94",
                        "2012-03-31",
                        "Out",
                        "10",
                        "10",
                        "False",
                        "Monthly",
                        "False"});
#line 477
 testRunner.Given("I have this schedule to create", ((string)(null)), table34);
#line 480
 testRunner.And("it has no Details");
#line 481
 testRunner.And("it has a Category");
#line 482
 testRunner.And("it has an Account Out");
#line 483
 testRunner.And("it has no Account In");
#line 484
 testRunner.When("I try to save the schedule");
#line 485
 testRunner.Then("I will receive no core error");
#line 486
 testRunner.And("the schedule will be saved");
#line 487
 testRunner.And("the accountOut value will not change");
#line 488
 testRunner.And("the month-category-accountOut value will not change");
#line 489
 testRunner.And("the year-category-accountOut value will not change");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("95. Save with info all right (details) (S)")]
        public virtual void _95_SaveWithInfoAllRightDetailsS()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("95. Save with info all right (details) (S)", ((string[])(null)));
#line 491
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table35 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value",
                        "Times",
                        "Boundless",
                        "Frequency",
                        "ShowInstallment"});
            table35.AddRow(new string[] {
                        "Move Da95",
                        "2012-03-31",
                        "Out",
                        "",
                        "10",
                        "False",
                        "Monthly",
                        "False"});
#line 492
 testRunner.Given("I have this schedule to create", ((string)(null)), table35);
#line hidden
            TechTalk.SpecFlow.Table table36 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Amount",
                        "Value"});
            table36.AddRow(new string[] {
                        "Detail 1",
                        "1",
                        "10"});
            table36.AddRow(new string[] {
                        "Detail 2",
                        "1",
                        "10"});
#line 495
 testRunner.And("the move has this details", ((string)(null)), table36);
#line 499
 testRunner.And("it has a Category");
#line 500
 testRunner.And("it has an Account Out");
#line 501
 testRunner.And("it has no Account In");
#line 502
 testRunner.When("I try to save the schedule");
#line 503
 testRunner.Then("I will receive no core error");
#line 504
 testRunner.And("the schedule will be saved");
#line 505
 testRunner.And("the accountOut value will not change");
#line 506
 testRunner.And("the month-category-accountOut value will not change");
#line 507
 testRunner.And("the year-category-accountOut value will not change");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("96. Save negative (value) (S)")]
        public virtual void _96_SaveNegativeValueS()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("96. Save negative (value) (S)", ((string[])(null)));
#line 509
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table37 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value",
                        "Times",
                        "Boundless",
                        "Frequency",
                        "ShowInstallment"});
            table37.AddRow(new string[] {
                        "Move Da96",
                        "2012-03-31",
                        "Out",
                        "-10",
                        "10",
                        "False",
                        "Monthly",
                        "False"});
#line 510
 testRunner.Given("I have this schedule to create", ((string)(null)), table37);
#line 513
 testRunner.And("it has no Details");
#line 514
 testRunner.And("it has a Category");
#line 515
 testRunner.And("it has an Account Out");
#line 516
 testRunner.And("it has no Account In");
#line 517
 testRunner.When("I try to save the schedule");
#line 518
 testRunner.Then("I will receive no core error");
#line 519
 testRunner.And("the schedule will be saved");
#line 520
 testRunner.And("the accountOut value will not change");
#line 521
 testRunner.And("the month-category-accountOut value will not change");
#line 522
 testRunner.And("the year-category-accountOut value will not change");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("97. Save negative (details) (S)")]
        public virtual void _97_SaveNegativeDetailsS()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("97. Save negative (details) (S)", ((string[])(null)));
#line 524
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table38 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value",
                        "Times",
                        "Boundless",
                        "Frequency",
                        "ShowInstallment"});
            table38.AddRow(new string[] {
                        "Move Da97",
                        "2012-03-31",
                        "Out",
                        "",
                        "10",
                        "False",
                        "Monthly",
                        "False"});
#line 525
 testRunner.Given("I have this schedule to create", ((string)(null)), table38);
#line hidden
            TechTalk.SpecFlow.Table table39 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Amount",
                        "Value"});
            table39.AddRow(new string[] {
                        "Detail 1",
                        "1",
                        "-10"});
            table39.AddRow(new string[] {
                        "Detail 2",
                        "1",
                        "10"});
#line 528
 testRunner.And("the move has this details", ((string)(null)), table39);
#line 532
 testRunner.And("it has a Category");
#line 533
 testRunner.And("it has an Account Out");
#line 534
 testRunner.And("it has no Account In");
#line 535
 testRunner.When("I try to save the schedule");
#line 536
 testRunner.Then("I will receive no core error");
#line 537
 testRunner.And("the schedule will be saved");
#line 538
 testRunner.And("the accountOut value will not change");
#line 539
 testRunner.And("the month-category-accountOut value will not change");
#line 540
 testRunner.And("the year-category-accountOut value will not change");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("98. Save with future Date (E)")]
        public virtual void _98_SaveWithFutureDateE()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("98. Save with future Date (E)", ((string[])(null)));
#line 542
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table40 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value",
                        "Times",
                        "Boundless",
                        "Frequency",
                        "ShowInstallment"});
            table40.AddRow(new string[] {
                        "Move Da98",
                        "2099-03-31",
                        "Out",
                        "10",
                        "10",
                        "False",
                        "Monthly",
                        "False"});
#line 543
 testRunner.Given("I have this schedule to create", ((string)(null)), table40);
#line 546
 testRunner.And("it has no Details");
#line 547
 testRunner.And("it has a Category");
#line 548
 testRunner.And("it has an Account Out");
#line 549
 testRunner.And("it has no Account In");
#line 550
 testRunner.When("I try to save the schedule");
#line 551
 testRunner.Then("I will receive no core error");
#line 552
 testRunner.And("the schedule will be saved");
#line 553
 testRunner.And("the accountOut value will not change");
#line 554
 testRunner.And("the month-category-accountOut value will not change");
#line 555
 testRunner.And("the year-category-accountOut value will not change");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("99. Save with exactly length in Description of Detail (S)")]
        public virtual void _99_SaveWithExactlyLengthInDescriptionOfDetailS()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("99. Save with exactly length in Description of Detail (S)", ((string[])(null)));
#line 557
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table41 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value",
                        "Times",
                        "Boundless",
                        "Frequency",
                        "ShowInstallment"});
            table41.AddRow(new string[] {
                        "Move Da99",
                        "2010-03-31",
                        "Out",
                        "",
                        "10",
                        "False",
                        "Monthly",
                        "False"});
#line 558
 testRunner.Given("I have this schedule to create", ((string)(null)), table41);
#line hidden
            TechTalk.SpecFlow.Table table42 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Amount",
                        "Value"});
            table42.AddRow(new string[] {
                        "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwx",
                        "1",
                        "10"});
#line 561
 testRunner.And("the move has this details", ((string)(null)), table42);
#line 564
 testRunner.And("it has a Category");
#line 565
 testRunner.And("it has an Account Out");
#line 566
 testRunner.And("it has no Account In");
#line 567
 testRunner.When("I try to save the schedule");
#line 568
 testRunner.Then("I will receive no core error");
#line 569
 testRunner.And("the schedule will be saved");
#line 570
 testRunner.And("the accountOut value will not change");
#line 571
 testRunner.And("the month-category-accountOut value will not change");
#line 572
 testRunner.And("the year-category-accountOut value will not change");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("9A. Save with exactly length in Description (S)")]
        public virtual void _9A_SaveWithExactlyLengthInDescriptionS()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("9A. Save with exactly length in Description (S)", ((string[])(null)));
#line 574
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table43 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value",
                        "Times",
                        "Boundless",
                        "Frequency",
                        "ShowInstallment"});
            table43.AddRow(new string[] {
                        "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwx",
                        "2010-03-31",
                        "Out",
                        "10",
                        "10",
                        "False",
                        "Monthly",
                        "False"});
#line 575
 testRunner.Given("I have this schedule to create", ((string)(null)), table43);
#line 578
 testRunner.And("it has no Details");
#line 579
 testRunner.And("it has a Category");
#line 580
 testRunner.And("it has an Account Out");
#line 581
 testRunner.And("it has no Account In");
#line 582
 testRunner.When("I try to save the schedule");
#line 583
 testRunner.Then("I will receive no core error");
#line 584
 testRunner.And("the schedule will be saved");
#line 585
 testRunner.And("the accountOut value will not change");
#line 586
 testRunner.And("the month-category-accountOut value will not change");
#line 587
 testRunner.And("the year-category-accountOut value will not change");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("9B. Save with details with same description (S)")]
        public virtual void _9B_SaveWithDetailsWithSameDescriptionS()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("9B. Save with details with same description (S)", ((string[])(null)));
#line 589
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table44 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value",
                        "Times",
                        "Boundless",
                        "Frequency",
                        "ShowInstallment"});
            table44.AddRow(new string[] {
                        "Move Da9D",
                        "2012-03-31",
                        "Out",
                        "",
                        "10",
                        "False",
                        "Monthly",
                        "False"});
#line 590
 testRunner.Given("I have this schedule to create", ((string)(null)), table44);
#line hidden
            TechTalk.SpecFlow.Table table45 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Amount",
                        "Value"});
            table45.AddRow(new string[] {
                        "Move Da9D",
                        "1",
                        "10"});
#line 593
 testRunner.And("the schedule has this details", ((string)(null)), table45);
#line 596
 testRunner.And("it has a Category");
#line 597
 testRunner.And("it has an Account Out");
#line 598
 testRunner.And("it has no Account In");
#line 599
 testRunner.When("I try to save the schedule");
#line 600
 testRunner.Then("I will receive no core error");
#line 601
 testRunner.And("the schedule will be saved");
#line 602
 testRunner.And("the accountOut value will not change");
#line 603
 testRunner.And("the month-category-accountOut value will not change");
#line 604
 testRunner.And("the year-category-accountOut value will not change");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
