// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.6.1.0
//      SpecFlow Generator Version:1.6.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace DFM.Tests.BusinessLogic.A_Safe
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.6.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("m. Update E-mail")]
    public partial class M_UpdateE_MailFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "m.UpdateEmail.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "m. Update E-mail", "", GenerationTargetLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("01. E-mail change with wrong current password (E)")]
        public virtual void _01_E_MailChangeWithWrongCurrentPasswordE()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("01. E-mail change with wrong current password (E)", ((string[])(null)));
#line 3
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "Password"});
            table1.AddRow(new string[] {
                        "Am01@dontflymoney.com",
                        "password"});
#line 4
 testRunner.Given("I have this user created and activated", ((string)(null)), table1);
#line 7
 testRunner.And("I have a ticket of this user");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "New E-mail",
                        "Current Password"});
            table2.AddRow(new string[] {
                        "Am01_@dontflymoney.com",
                        "password_wrong"});
#line 8
 testRunner.And("I pass this new e-mail and password", ((string)(null)), table2);
#line 11
 testRunner.When("I try to change the e-mail");
#line 12
 testRunner.Then("I will receive this core error: WrongPassword");
#line 13
 testRunner.And("the e-mail will not be changed");
#line 14
 testRunner.And("the user will be activated");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("02. E-mail change with empty new e-mail (E)")]
        public virtual void _02_E_MailChangeWithEmptyNewE_MailE()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("02. E-mail change with empty new e-mail (E)", ((string[])(null)));
#line 16
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "Password"});
            table3.AddRow(new string[] {
                        "Am02@dontflymoney.com",
                        "password"});
#line 17
 testRunner.Given("I have this user created and activated", ((string)(null)), table3);
#line 20
 testRunner.And("I have a ticket of this user");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "New E-mail",
                        "Current Password"});
            table4.AddRow(new string[] {
                        "",
                        "password"});
#line 21
 testRunner.And("I pass this new e-mail and password", ((string)(null)), table4);
#line 24
 testRunner.When("I try to change the e-mail");
#line 25
 testRunner.Then("I will receive this core error: UserEmailInvalid");
#line 26
 testRunner.And("the e-mail will not be changed");
#line 27
 testRunner.And("the user will be activated");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("99. E-mail change with info all right (S)")]
        public virtual void _99_E_MailChangeWithInfoAllRightS()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("99. E-mail change with info all right (S)", ((string[])(null)));
#line 30
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "Password"});
            table5.AddRow(new string[] {
                        "Am99@dontflymoney.com",
                        "password"});
#line 31
 testRunner.Given("I have this user created and activated", ((string)(null)), table5);
#line 34
 testRunner.And("I have a ticket of this user");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "New E-mail",
                        "Current Password"});
            table6.AddRow(new string[] {
                        "Am99_@dontflymoney.com",
                        "password"});
#line 35
 testRunner.And("I pass this new e-mail and password", ((string)(null)), table6);
#line 38
 testRunner.When("I try to change the e-mail");
#line 39
 testRunner.Then("I will receive no core error");
#line 40
 testRunner.And("the e-mail will be changed");
#line 41
 testRunner.And("the user will not be activated");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
