// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.6.1.0
//      SpecFlow Generator Version:1.6.0.0
//      Runtime Version:4.0.30319.18444
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace DFM.Tests.BusinessLogic.E_Report
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.6.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("a. Month report")]
    public partial class A_MonthReportFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "a.GetMonthReport.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "a. Month report", "", GenerationTargetLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            this.FeatureBackground();
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void FeatureBackground()
        {
#line 3
#line 4
 testRunner.Given("I have an active user");
#line 5
 testRunner.And("I enable Categories use");
#line 6
 testRunner.And("I have an account");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Date"});
            table1.AddRow(new string[] {
                        "2012-03-27"});
            table1.AddRow(new string[] {
                        "2012-03-28"});
            table1.AddRow(new string[] {
                        "2012-03-29"});
            table1.AddRow(new string[] {
                        "2012-03-30"});
            table1.AddRow(new string[] {
                        "2012-03-31"});
            table1.AddRow(new string[] {
                        "2012-04-01"});
            table1.AddRow(new string[] {
                        "2012-04-02"});
            table1.AddRow(new string[] {
                        "2012-04-03"});
            table1.AddRow(new string[] {
                        "2012-04-04"});
            table1.AddRow(new string[] {
                        "2012-04-05"});
            table1.AddRow(new string[] {
                        "2012-04-06"});
#line 7
 testRunner.And("I have moves of", ((string)(null)), table1);
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("01. Get with invalid Account name (E)")]
        public virtual void _01_GetWithInvalidAccountNameE()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("01. Get with invalid Account name (E)", ((string[])(null)));
#line 21
this.ScenarioSetup(scenarioInfo);
#line 22
 testRunner.Given("I pass an invalid account url");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Month",
                        "Year"});
            table2.AddRow(new string[] {
                        "4",
                        "2012"});
#line 23
 testRunner.And("I pass this date", ((string)(null)), table2);
#line 26
 testRunner.When("I try to get the month report");
#line 27
 testRunner.Then("I will receive this core error: InvalidAccount");
#line 28
 testRunner.And("I will receive no month report");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("02. Get with Date Year Zero (E)")]
        public virtual void _02_GetWithDateYearZeroE()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("02. Get with Date Year Zero (E)", ((string[])(null)));
#line 30
this.ScenarioSetup(scenarioInfo);
#line 31
 testRunner.Given("I pass a valid account url");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Month",
                        "Year"});
            table3.AddRow(new string[] {
                        "4",
                        "0"});
#line 32
 testRunner.And("I pass this date", ((string)(null)), table3);
#line 35
 testRunner.When("I try to get the month report");
#line 36
 testRunner.Then("I will receive this core error: InvalidYear");
#line 37
 testRunner.And("I will receive no month report");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("03. Get with Date Month less than 1 (E)")]
        public virtual void _03_GetWithDateMonthLessThan1E()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("03. Get with Date Month less than 1 (E)", ((string[])(null)));
#line 39
this.ScenarioSetup(scenarioInfo);
#line 40
 testRunner.Given("I pass a valid account url");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Month",
                        "Year"});
            table4.AddRow(new string[] {
                        "0",
                        "2012"});
#line 41
 testRunner.And("I pass this date", ((string)(null)), table4);
#line 44
 testRunner.When("I try to get the month report");
#line 45
 testRunner.Then("I will receive this core error: InvalidMonth");
#line 46
 testRunner.And("I will receive no month report");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("04. Get with Date Month more than 12 (E)")]
        public virtual void _04_GetWithDateMonthMoreThan12E()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("04. Get with Date Month more than 12 (E)", ((string[])(null)));
#line 48
this.ScenarioSetup(scenarioInfo);
#line 49
 testRunner.Given("I pass a valid account url");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Month",
                        "Year"});
            table5.AddRow(new string[] {
                        "13",
                        "2012"});
#line 50
 testRunner.And("I pass this date", ((string)(null)), table5);
#line 53
 testRunner.When("I try to get the month report");
#line 54
 testRunner.Then("I will receive this core error: InvalidMonth");
#line 55
 testRunner.And("I will receive no month report");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("99. Get with info all right (S)")]
        public virtual void _99_GetWithInfoAllRightS()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("99. Get with info all right (S)", ((string[])(null)));
#line 59
this.ScenarioSetup(scenarioInfo);
#line 60
 testRunner.Given("I pass a valid account url");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Month",
                        "Year"});
            table6.AddRow(new string[] {
                        "4",
                        "2012"});
#line 61
 testRunner.And("I pass this date", ((string)(null)), table6);
#line 64
 testRunner.When("I try to get the month report");
#line 65
 testRunner.Then("I will receive no core error");
#line 66
 testRunner.And("I will receive the month report");
#line 67
 testRunner.And("its sum value will be equal to its moves sum value");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
