Feature: Cc. Get move

Background:
	Given I have a complete user logged in
		And I enable Categories use
		And I have two accounts
		And I have a category
		And I have a move

Scenario: Cc01. Try to get Move with wrong ID
	Given I pass an id of Move that doesn't exist
	When I try to get the move
	Then I will receive this core error: InvalidMove
		And I will receive no move

Scenario: Cc02. Get the Move by ID
	Given I pass valid Move ID
	When I try to get the move
	Then I will receive no core error
		And I will receive the move

Scenario: Cc03. Get another user's Move
	Given I pass valid Move ID
		But there is a bad person logged in
	When I try to get the move
	Then I will receive this core error: InvalidMove
		And I will receive no move

Scenario: Cc04. Get move generated by schedule
	Given I have this schedule to create
			| Description   | Date       | Nature | Value | Times | Boundless | Frequency | ShowInstallment |
			| Schedule Cc04 | 2020-01-04 | Out    | 10    | 1     | False     | Monthly   | True            |
		And it has no Details
		And it has a Category
		And it has an Account Out
		And it has no Account In
		And I save the schedule
		And I run the scheduler
		And I pass the first schedule move ID
	When I try to get the move
	Then I will receive no core error
		And the Move description will be Schedule Cc04
