ALTER TABLE User
	ADD COLUMN Active bit not null default 0;

CREATE TABLE Security (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	Active BIT NOT NULL,
	Expire datetime NOT NULL,
	Action TINYINT NOT NULL,
	Sent BIT NOT NULL,
	User_ID INTEGER NOT NULL,
	Token varchar(50) NOT NULL,
	PRIMARY KEY (ID),
	UNIQUE KEY Token (Token),
	KEY User_ID (User_ID),
	CONSTRAINT FKAAE052DE8EFD2E71 FOREIGN KEY (User_ID) REFERENCES user (ID)
);
