CREATE TABLE Contract
(
	ID INT NOT NULL AUTO_INCREMENT,
	BeginDate DATETIME NOT NULL,
	Version VARCHAR(12) NOT NULL,

	CONSTRAINT PK_Contract
		PRIMARY KEY (ID),
		
	CONSTRAINT UK_Contract
		UNIQUE KEY (Version)
);

CREATE TABLE Acceptance
(
	ID INT NOT NULL AUTO_INCREMENT,
	Accepted BIT NOT NULL,
	CreateDate DATETIME NOT NULL,
	AcceptDate DATETIME NOT NULL,
	Contract_ID INT NOT NULL,
	User_ID INT NOT NULL,
	
	CONSTRAINT PK_Acceptance
		PRIMARY KEY (ID),
		
	CONSTRAINT FK_Acceptance_Contract
		FOREIGN KEY (Contract_ID)
		REFERENCES Contract (ID),
		
	CONSTRAINT FK_Acceptance_User
		FOREIGN KEY (User_ID)
		REFERENCES User (ID),
		
	CONSTRAINT UK_Acceptance
		UNIQUE KEY (User_ID, Contract_ID)
);

INSERT INTO Contract (BeginDate, Version) VALUES (now(), '003000000000');