CREATE TABLE contract
(
	ID INT NOT NULL AUTO_INCREMENT,
	BeginDate DATETIME NOT NULL,
	Version VARCHAR(12) NOT NULL,

	CONSTRAINT PK_Contract
		PRIMARY KEY (ID),

	CONSTRAINT UK_Contract
		UNIQUE KEY (Version)
);

CREATE TABLE acceptance
(
	ID INT NOT NULL AUTO_INCREMENT,
	Accepted BIT NOT NULL,
	CreateDate DATETIME NOT NULL,
	AcceptDate DATETIME NOT NULL,
	Contract_ID INT NOT NULL,
	User_ID INT NOT NULL,

	CONSTRAINT PK_Acceptance
		PRIMARY KEY (ID),

	CONSTRAINT FK_Acceptance_Contract
		FOREIGN KEY (Contract_ID)
		REFERENCES contract (ID),

	CONSTRAINT FK_Acceptance_User
		FOREIGN KEY (User_ID)
		REFERENCES user (ID),

	CONSTRAINT UK_Acceptance
		UNIQUE KEY (User_ID, Contract_ID)
);

INSERT INTO contract (BeginDate, Version) VALUES (now(), '003000000000');

ALTER TABLE config
	ADD COLUMN Theme SMALLINT;

SET SQL_SAFE_UPDATES = 0;

UPDATE config
	SET Theme = 2;

SET SQL_SAFE_UPDATES = 1;
