Feature: Ea. Get month report

Background:
	Given I have a complete user logged in
		And I enable Categories use
		And I have an account
		And I have moves of
			| Date       |
			| 2012-03-27 |
			| 2012-03-28 |
			| 2012-03-29 |
			| 2012-03-30 |
			| 2012-03-31 |
			| 2012-04-01 |
			| 2012-04-02 |
			| 2012-04-03 |
			| 2012-04-04 |
			| 2012-04-05 |
			| 2012-04-06 |

Scenario: Ea01. Get with invalid Account name
	Given I pass an invalid account url
		And I pass this date
			| Month | Year |
			| 4     | 2012 |
	When I try to get the month report
	Then I will receive this core error: InvalidAccount
		And I will receive no month report

Scenario: Ea02. Get with Date Year Zero
	Given I pass a valid account url
		And I pass this date
			| Month | Year |
			| 4     | 0    |
	When I try to get the month report
	Then I will receive this core error: InvalidYear
		And I will receive no month report

Scenario: Ea03. Get with Date Month less than 1
	Given I pass a valid account url
		And I pass this date
			| Month | Year |
			| 0     | 2012 |
	When I try to get the month report
	Then I will receive this core error: InvalidMonth
		And I will receive no month report

Scenario: Ea04. Get with Date Month more than 12
	Given I pass a valid account url
		And I pass this date
			| Month | Year |
			| 13    | 2012 |
	When I try to get the month report
	Then I will receive this core error: InvalidMonth
		And I will receive no month report

Scenario: Ea05. Get with next year date
	Given I have moves of
			| Date       |
			| +0         |
		And I pass a valid account url
		And I pass this date
			| Month | Year |
			| +0    | +1   |
	When I try to get the month report
	Then I will receive no core error
		And I will receive the month report
		And there will be no moves

Scenario: Ea06. Get with info all right
	Given I pass a valid account url
		And I pass this date
			| Month | Year |
			| 4     | 2012 |
	When I try to get the month report
	Then I will receive no core error
		And I will receive the month report
		And its sum value will be equal to its moves sum value

Scenario: Ea07. Get move generated by schedule - without Installment
	Given I have this schedule to create
			| Description   | Date       | Nature | Value | Times | Boundless | Frequency | ShowInstallment |
			| Schedule Ea07 | 2020-01-04 | Out    | 10    | 1     | False     | Monthly   | False           |
		And it has no Details
		And it has a Category
		And it has an Account Out
		And it has no Account In
		And I save the schedule
		And I run the scheduler
		And I pass Account Out url
		And I pass this date
			| Month | Year |
			| 1     | 2020 |
	When I try to get the month report
	Then I will receive no core error
		And I will receive the month report
		And there will have a move with description Schedule Ea07

Scenario: Ea08. Get move generated by schedule - bounded with Installment
	Given I have this schedule to create
			| Description   | Date       | Nature | Value | Times | Boundless | Frequency | ShowInstallment |
			| Schedule Ea08 | 2020-01-04 | Out    | 10    | 2     | False     | Monthly   | True            |
		And it has no Details
		And it has a Category
		And it has an Account Out
		And it has no Account In
		And I save the schedule
		And I run the scheduler
		And I pass Account Out url
		And I pass this date
			| Month | Year |
			| 1     | 2020 |
	When I try to get the month report
	Then I will receive no core error
		And I will receive the month report
		And there will have a move with description Schedule Ea08 [1/2]

Scenario: Ea09. Get report with the move generated by schedule - boundless with Installment
	Given I have this schedule to create
			| Description   | Date       | Nature | Value | Times | Boundless | Frequency | ShowInstallment |
			| Schedule Ea09 | 2020-01-04 | Out    | 10    |       | True      | Monthly   | True            |
		And it has no Details
		And it has a Category
		And it has an Account Out
		And it has no Account In
		And I save the schedule
		And I run the scheduler
		And I pass Account Out url
		And I pass this date
			| Month | Year |
			| 1     | 2020 |
	When I try to get the month report
	Then I will receive no core error
		And I will receive the month report
		And there will have a move with description Schedule Ea09 [1]
