// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.6.1.0
//      SpecFlow Generator Version:1.6.0.0
//      Runtime Version:4.0.30319.261
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace DFM.Tests.C_Money
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.6.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("a. Creation of Move")]
    public partial class A_CreationOfMoveFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "a.SaveMove.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "a. Creation of Move", "", GenerationTargetLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            this.FeatureBackground();
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void FeatureBackground()
        {
#line 3
#line 4
 testRunner.Given("I have an user");
#line 5
 testRunner.And("I have two accounts");
#line 6
 testRunner.And("I have a category");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("01. Save without Description (E)")]
        public virtual void _01_SaveWithoutDescriptionE()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("01. Save without Description (E)", ((string[])(null)));
#line 8
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value"});
            table1.AddRow(new string[] {
                        "",
                        "2012-03-31",
                        "Out",
                        "10"});
#line 9
 testRunner.Given("I have this move to create", ((string)(null)), table1);
#line 12
 testRunner.And("it has no Details");
#line 13
 testRunner.And("it has a Category");
#line 14
 testRunner.And("it has an Account Out");
#line 15
 testRunner.And("it has no Account In");
#line 16
 testRunner.When("I try to save the move");
#line 17
 testRunner.Then("I will receive this error: MoveDescriptionRequired");
#line 18
 testRunner.And("the move will not be saved");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("02. Save without Date (E)")]
        public virtual void _02_SaveWithoutDateE()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("02. Save without Date (E)", ((string[])(null)));
#line 20
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value"});
            table2.AddRow(new string[] {
                        "Move Ca02",
                        "",
                        "Out",
                        "10"});
#line 21
 testRunner.Given("I have this move to create", ((string)(null)), table2);
#line 24
 testRunner.And("it has no Details");
#line 25
 testRunner.And("it has a Category");
#line 26
 testRunner.And("it has an Account Out");
#line 27
 testRunner.And("it has no Account In");
#line 28
 testRunner.When("I try to save the move");
#line 29
 testRunner.Then("I will receive this error: MoveDateRequired");
#line 30
 testRunner.And("the move will not be saved");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("03. Save with future Date (E)")]
        public virtual void _03_SaveWithFutureDateE()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("03. Save with future Date (E)", ((string[])(null)));
#line 32
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value"});
            table3.AddRow(new string[] {
                        "Move Ca03",
                        "2099-03-31",
                        "Out",
                        "10"});
#line 33
 testRunner.Given("I have this move to create", ((string)(null)), table3);
#line 36
 testRunner.And("it has no Details");
#line 37
 testRunner.And("it has a Category");
#line 38
 testRunner.And("it has an Account Out");
#line 39
 testRunner.And("it has no Account In");
#line 40
 testRunner.When("I try to save the move");
#line 41
 testRunner.Then("I will receive this error: MoveDateInvalid");
#line 42
 testRunner.And("the move will not be saved");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("04. Save without Category (E)")]
        public virtual void _04_SaveWithoutCategoryE()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("04. Save without Category (E)", ((string[])(null)));
#line 44
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value"});
            table4.AddRow(new string[] {
                        "Move Ca04",
                        "2012-03-31",
                        "Out",
                        "10"});
#line 45
 testRunner.Given("I have this move to create", ((string)(null)), table4);
#line 48
 testRunner.And("it has no Details");
#line 49
 testRunner.And("it has no Category");
#line 50
 testRunner.And("it has an Account Out");
#line 51
 testRunner.And("it has no Account In");
#line 52
 testRunner.When("I try to save the move");
#line 53
 testRunner.Then("I will receive this error: MoveCategoryRequired");
#line 54
 testRunner.And("the move will not be saved");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("05. Save with unknown Category (E)")]
        public virtual void _05_SaveWithUnknownCategoryE()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("05. Save with unknown Category (E)", ((string[])(null)));
#line 56
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value"});
            table5.AddRow(new string[] {
                        "Move Ca05",
                        "2012-03-31",
                        "Out",
                        "10"});
#line 57
 testRunner.Given("I have this move to create", ((string)(null)), table5);
#line 60
 testRunner.And("it has no Details");
#line 61
 testRunner.And("it has an unknown Category");
#line 62
 testRunner.And("it has an Account Out");
#line 63
 testRunner.And("it has no Account In");
#line 64
 testRunner.When("I try to save the move");
#line 65
 testRunner.Then("I will receive this error: MoveCategoryInvalid");
#line 66
 testRunner.And("the move will not be saved");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("11. Save with (Nature: Out) (AccountOut:No) (AccountIn:No) (E)")]
        public virtual void _11_SaveWithNatureOutAccountOutNoAccountInNoE()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("11. Save with (Nature: Out) (AccountOut:No) (AccountIn:No) (E)", ((string[])(null)));
#line 70
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value"});
            table6.AddRow(new string[] {
                        "Move Ca11",
                        "2012-03-31",
                        "Out",
                        "10"});
#line 71
 testRunner.Given("I have this move to create", ((string)(null)), table6);
#line 74
 testRunner.And("it has no Details");
#line 75
 testRunner.And("it has a Category");
#line 76
 testRunner.And("it has no Account Out");
#line 77
 testRunner.And("it has no Account In");
#line 78
 testRunner.When("I try to save the move");
#line 79
 testRunner.Then("I will receive this error: OutMoveWrong");
#line 80
 testRunner.And("the move will not be saved");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("12. Save with (Nature: Out) (AccountOut:Yes) (AccountIn:Yes) (E)")]
        public virtual void _12_SaveWithNatureOutAccountOutYesAccountInYesE()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("12. Save with (Nature: Out) (AccountOut:Yes) (AccountIn:Yes) (E)", ((string[])(null)));
#line 82
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value"});
            table7.AddRow(new string[] {
                        "Move Ca12",
                        "2012-03-31",
                        "Out",
                        "10"});
#line 83
 testRunner.Given("I have this move to create", ((string)(null)), table7);
#line 86
 testRunner.And("it has no Details");
#line 87
 testRunner.And("it has a Category");
#line 88
 testRunner.And("it has an Account Out");
#line 89
 testRunner.And("it has an Account In");
#line 90
 testRunner.When("I try to save the move");
#line 91
 testRunner.Then("I will receive this error: OutMoveWrong");
#line 92
 testRunner.And("the move will not be saved");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("13. Save with (Nature: Out) (AccountOut:No) (AccountIn:Yes) (E)")]
        public virtual void _13_SaveWithNatureOutAccountOutNoAccountInYesE()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("13. Save with (Nature: Out) (AccountOut:No) (AccountIn:Yes) (E)", ((string[])(null)));
#line 94
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value"});
            table8.AddRow(new string[] {
                        "Move Ca13",
                        "2012-03-31",
                        "Out",
                        "10"});
#line 95
 testRunner.Given("I have this move to create", ((string)(null)), table8);
#line 98
 testRunner.And("it has no Details");
#line 99
 testRunner.And("it has a Category");
#line 100
 testRunner.And("it has no Account Out");
#line 101
 testRunner.And("it has an Account In");
#line 102
 testRunner.When("I try to save the move");
#line 103
 testRunner.Then("I will receive this error: OutMoveWrong");
#line 104
 testRunner.And("the move will not be saved");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("14. Save with (Nature: Out) (AccountOut:Unknown) (AccountIn:No) (E)")]
        public virtual void _14_SaveWithNatureOutAccountOutUnknownAccountInNoE()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("14. Save with (Nature: Out) (AccountOut:Unknown) (AccountIn:No) (E)", ((string[])(null)));
#line 106
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value"});
            table9.AddRow(new string[] {
                        "Move Ca14",
                        "2012-03-31",
                        "Out",
                        "10"});
#line 107
 testRunner.Given("I have this move to create", ((string)(null)), table9);
#line 110
 testRunner.And("it has no Details");
#line 111
 testRunner.And("it has a Category");
#line 112
 testRunner.And("it has an unknown Account Out");
#line 113
 testRunner.And("it has no Account In");
#line 114
 testRunner.When("I try to save the move");
#line 115
 testRunner.Then("I will receive this error: OutMoveWrong");
#line 116
 testRunner.And("the move will not be saved");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("21. Save with (Nature: In) (AccountOut:No) (AccountIn:No) (E)")]
        public virtual void _21_SaveWithNatureInAccountOutNoAccountInNoE()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("21. Save with (Nature: In) (AccountOut:No) (AccountIn:No) (E)", ((string[])(null)));
#line 120
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value"});
            table10.AddRow(new string[] {
                        "Move Ca21",
                        "2012-03-31",
                        "In",
                        "10"});
#line 121
 testRunner.Given("I have this move to create", ((string)(null)), table10);
#line 124
 testRunner.And("it has no Details");
#line 125
 testRunner.And("it has a Category");
#line 126
 testRunner.And("it has no Account Out");
#line 127
 testRunner.And("it has no Account In");
#line 128
 testRunner.When("I try to save the move");
#line 129
 testRunner.Then("I will receive this error: InMoveWrong");
#line 130
 testRunner.And("the move will not be saved");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("22. Save with (Nature: In) (AccountOut:Yes) (AccountIn:Yes) (E)")]
        public virtual void _22_SaveWithNatureInAccountOutYesAccountInYesE()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("22. Save with (Nature: In) (AccountOut:Yes) (AccountIn:Yes) (E)", ((string[])(null)));
#line 132
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value"});
            table11.AddRow(new string[] {
                        "Move Ca22",
                        "2012-03-31",
                        "In",
                        "10"});
#line 133
 testRunner.Given("I have this move to create", ((string)(null)), table11);
#line 136
 testRunner.And("it has no Details");
#line 137
 testRunner.And("it has a Category");
#line 138
 testRunner.And("it has an Account Out");
#line 139
 testRunner.And("it has an Account In");
#line 140
 testRunner.When("I try to save the move");
#line 141
 testRunner.Then("I will receive this error: InMoveWrong");
#line 142
 testRunner.And("the move will not be saved");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("23. Save with (Nature: In) (AccountOut:Yes) (AccountIn:No) (E)")]
        public virtual void _23_SaveWithNatureInAccountOutYesAccountInNoE()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("23. Save with (Nature: In) (AccountOut:Yes) (AccountIn:No) (E)", ((string[])(null)));
#line 144
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value"});
            table12.AddRow(new string[] {
                        "Move Ca23",
                        "2012-03-31",
                        "In",
                        "10"});
#line 145
 testRunner.Given("I have this move to create", ((string)(null)), table12);
#line 148
 testRunner.And("it has no Details");
#line 149
 testRunner.And("it has a Category");
#line 150
 testRunner.And("it has an Account Out");
#line 151
 testRunner.And("it has no Account In");
#line 152
 testRunner.When("I try to save the move");
#line 153
 testRunner.Then("I will receive this error: InMoveWrong");
#line 154
 testRunner.And("the move will not be saved");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("24. Save with (Nature: In) (AccountOut:No) (AccountIn:Unknown) (E)")]
        public virtual void _24_SaveWithNatureInAccountOutNoAccountInUnknownE()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("24. Save with (Nature: In) (AccountOut:No) (AccountIn:Unknown) (E)", ((string[])(null)));
#line 156
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value"});
            table13.AddRow(new string[] {
                        "Move Ca24",
                        "2012-03-31",
                        "In",
                        "10"});
#line 157
 testRunner.Given("I have this move to create", ((string)(null)), table13);
#line 160
 testRunner.And("it has no Details");
#line 161
 testRunner.And("it has a Category");
#line 162
 testRunner.And("it has no Account Out");
#line 163
 testRunner.And("it has an unknown Account In");
#line 164
 testRunner.When("I try to save the move");
#line 165
 testRunner.Then("I will receive this error: InMoveWrong");
#line 166
 testRunner.And("the move will not be saved");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("31. Save with (Nature: Transfer) (AccountOut:No) (AccountIn:No) (E)")]
        public virtual void _31_SaveWithNatureTransferAccountOutNoAccountInNoE()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("31. Save with (Nature: Transfer) (AccountOut:No) (AccountIn:No) (E)", ((string[])(null)));
#line 170
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value"});
            table14.AddRow(new string[] {
                        "Move Ca31",
                        "2012-03-31",
                        "Transfer",
                        "10"});
#line 171
 testRunner.Given("I have this move to create", ((string)(null)), table14);
#line 174
 testRunner.And("it has no Details");
#line 175
 testRunner.And("it has a Category");
#line 176
 testRunner.And("it has no Account Out");
#line 177
 testRunner.And("it has no Account In");
#line 178
 testRunner.When("I try to save the move");
#line 179
 testRunner.Then("I will receive this error: TransferMoveWrong");
#line 180
 testRunner.And("the move will not be saved");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("32. Save with (Nature: Transfer) (AccountOut:No) (AccountIn:Yes) (E)")]
        public virtual void _32_SaveWithNatureTransferAccountOutNoAccountInYesE()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("32. Save with (Nature: Transfer) (AccountOut:No) (AccountIn:Yes) (E)", ((string[])(null)));
#line 182
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value"});
            table15.AddRow(new string[] {
                        "Move Ca32",
                        "2012-03-31",
                        "Transfer",
                        "10"});
#line 183
 testRunner.Given("I have this move to create", ((string)(null)), table15);
#line 186
 testRunner.And("it has no Details");
#line 187
 testRunner.And("it has a Category");
#line 188
 testRunner.And("it has no Account Out");
#line 189
 testRunner.And("it has an Account In");
#line 190
 testRunner.When("I try to save the move");
#line 191
 testRunner.Then("I will receive this error: TransferMoveWrong");
#line 192
 testRunner.And("the move will not be saved");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("33. Save with (Nature: Transfer) (AccountOut:Yes) (AccountIn:No) (E)")]
        public virtual void _33_SaveWithNatureTransferAccountOutYesAccountInNoE()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("33. Save with (Nature: Transfer) (AccountOut:Yes) (AccountIn:No) (E)", ((string[])(null)));
#line 194
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value"});
            table16.AddRow(new string[] {
                        "Move Ca33",
                        "2012-03-31",
                        "Transfer",
                        "10"});
#line 195
 testRunner.Given("I have this move to create", ((string)(null)), table16);
#line 198
 testRunner.And("it has no Details");
#line 199
 testRunner.And("it has a Category");
#line 200
 testRunner.And("it has an Account Out");
#line 201
 testRunner.And("it has no Account In");
#line 202
 testRunner.When("I try to save the move");
#line 203
 testRunner.Then("I will receive this error: TransferMoveWrong");
#line 204
 testRunner.And("the move will not be saved");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("34. Save with (Nature: Transfer) (AccountOut:Yes) (AccountIn:Unknown) (E)")]
        public virtual void _34_SaveWithNatureTransferAccountOutYesAccountInUnknownE()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("34. Save with (Nature: Transfer) (AccountOut:Yes) (AccountIn:Unknown) (E)", ((string[])(null)));
#line 206
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value"});
            table17.AddRow(new string[] {
                        "Move Ca34",
                        "2012-03-31",
                        "Transfer",
                        "10"});
#line 207
 testRunner.Given("I have this move to create", ((string)(null)), table17);
#line 210
 testRunner.And("it has no Details");
#line 211
 testRunner.And("it has a Category");
#line 212
 testRunner.And("it has an Account Out");
#line 213
 testRunner.And("it has an unknown Account In");
#line 214
 testRunner.When("I try to save the move");
#line 215
 testRunner.Then("I will receive this error: TransferMoveWrong");
#line 216
 testRunner.And("the move will not be saved");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("35. Save with (Nature: Transfer) (AccountOut:Unknown) (AccountIn:Yes) (E)")]
        public virtual void _35_SaveWithNatureTransferAccountOutUnknownAccountInYesE()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("35. Save with (Nature: Transfer) (AccountOut:Unknown) (AccountIn:Yes) (E)", ((string[])(null)));
#line 218
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value"});
            table18.AddRow(new string[] {
                        "Move Ca35",
                        "2012-03-31",
                        "Transfer",
                        "10"});
#line 219
 testRunner.Given("I have this move to create", ((string)(null)), table18);
#line 222
 testRunner.And("it has no Details");
#line 223
 testRunner.And("it has a Category");
#line 224
 testRunner.And("it has an unknown Account Out");
#line 225
 testRunner.And("it has an Account In");
#line 226
 testRunner.When("I try to save the move");
#line 227
 testRunner.Then("I will receive this error: TransferMoveWrong");
#line 228
 testRunner.And("the move will not be saved");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("36. Save with (Nature: Transfer) (AccountOut:Yes) (AccountIn:Equal to Out) (E)")]
        public virtual void _36_SaveWithNatureTransferAccountOutYesAccountInEqualToOutE()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("36. Save with (Nature: Transfer) (AccountOut:Yes) (AccountIn:Equal to Out) (E)", ((string[])(null)));
#line 230
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value"});
            table19.AddRow(new string[] {
                        "Move Ca35",
                        "2012-03-31",
                        "Transfer",
                        "10"});
#line 231
 testRunner.Given("I have this move to create", ((string)(null)), table19);
#line 234
 testRunner.And("it has no Details");
#line 235
 testRunner.And("it has a Category");
#line 236
 testRunner.And("it has an Account Out");
#line 237
 testRunner.And("it has an Account In equal to Out");
#line 238
 testRunner.When("I try to save the move");
#line 239
 testRunner.Then("I will receive this error: MoveCircularTransfer");
#line 240
 testRunner.And("the move will not be saved");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("41. Save without Value or Details (E)")]
        public virtual void _41_SaveWithoutValueOrDetailsE()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("41. Save without Value or Details (E)", ((string[])(null)));
#line 244
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value"});
            table20.AddRow(new string[] {
                        "Move Ca41",
                        "2012-03-31",
                        "Out",
                        ""});
#line 245
 testRunner.Given("I have this move to create", ((string)(null)), table20);
#line 248
 testRunner.And("it has no Details");
#line 249
 testRunner.And("it has a Category");
#line 250
 testRunner.And("it has an Account Out");
#line 251
 testRunner.And("it has no Account In");
#line 252
 testRunner.When("I try to save the move");
#line 253
 testRunner.Then("I will receive this error: MoveValueOrDetailRequired");
#line 254
 testRunner.And("the move will not be saved");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("42. Save with Value zero and no Details (E)")]
        public virtual void _42_SaveWithValueZeroAndNoDetailsE()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("42. Save with Value zero and no Details (E)", ((string[])(null)));
#line 256
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value"});
            table21.AddRow(new string[] {
                        "Move Ca42",
                        "2012-03-31",
                        "Out",
                        "0"});
#line 257
 testRunner.Given("I have this move to create", ((string)(null)), table21);
#line 260
 testRunner.And("it has no Details");
#line 261
 testRunner.And("it has a Category");
#line 262
 testRunner.And("it has an Account Out");
#line 263
 testRunner.And("it has no Account In");
#line 264
 testRunner.When("I try to save the move");
#line 265
 testRunner.Then("I will receive this error: MoveValueOrDetailRequired");
#line 266
 testRunner.And("the move will not be saved");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("43. Save without value and without Description in Detail (E)")]
        public virtual void _43_SaveWithoutValueAndWithoutDescriptionInDetailE()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("43. Save without value and without Description in Detail (E)", ((string[])(null)));
#line 268
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value"});
            table22.AddRow(new string[] {
                        "Move Ca43",
                        "2012-03-31",
                        "Out",
                        ""});
#line 269
 testRunner.Given("I have this move to create", ((string)(null)), table22);
#line hidden
            TechTalk.SpecFlow.Table table23 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Amount",
                        "Value"});
            table23.AddRow(new string[] {
                        "",
                        "1",
                        "10"});
            table23.AddRow(new string[] {
                        "Detail 2",
                        "1",
                        "10"});
#line 272
 testRunner.And("the move has this details", ((string)(null)), table23);
#line 276
 testRunner.And("it has a Category");
#line 277
 testRunner.And("it has an Account Out");
#line 278
 testRunner.And("it has no Account In");
#line 279
 testRunner.When("I try to save the move");
#line 280
 testRunner.Then("I will receive this error: MoveDetailDescriptionRequired");
#line 281
 testRunner.And("the move will not be saved");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("44. Save without value and with Amount zero in Detail (E)")]
        public virtual void _44_SaveWithoutValueAndWithAmountZeroInDetailE()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("44. Save without value and with Amount zero in Detail (E)", ((string[])(null)));
#line 283
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table24 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value"});
            table24.AddRow(new string[] {
                        "Move Ca44",
                        "2012-03-31",
                        "Out",
                        ""});
#line 284
 testRunner.Given("I have this move to create", ((string)(null)), table24);
#line hidden
            TechTalk.SpecFlow.Table table25 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Amount",
                        "Value"});
            table25.AddRow(new string[] {
                        "Detail 1",
                        "0",
                        "10"});
            table25.AddRow(new string[] {
                        "Detail 2",
                        "1",
                        "10"});
#line 287
 testRunner.And("the move has this details", ((string)(null)), table25);
#line 291
 testRunner.And("it has a Category");
#line 292
 testRunner.And("it has an Account Out");
#line 293
 testRunner.And("it has no Account In");
#line 294
 testRunner.When("I try to save the move");
#line 295
 testRunner.Then("I will receive this error: MoveDetailAmountRequired");
#line 296
 testRunner.And("the move will not be saved");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("45. Save without value and with Value zero in Detail (E)")]
        public virtual void _45_SaveWithoutValueAndWithValueZeroInDetailE()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("45. Save without value and with Value zero in Detail (E)", ((string[])(null)));
#line 298
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table26 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value"});
            table26.AddRow(new string[] {
                        "Move Ca45",
                        "2012-03-31",
                        "Out",
                        ""});
#line 299
 testRunner.Given("I have this move to create", ((string)(null)), table26);
#line hidden
            TechTalk.SpecFlow.Table table27 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Amount",
                        "Value"});
            table27.AddRow(new string[] {
                        "Detail 1",
                        "1",
                        "0"});
            table27.AddRow(new string[] {
                        "Detail 2",
                        "1",
                        "10"});
#line 302
 testRunner.And("the move has this details", ((string)(null)), table27);
#line 306
 testRunner.And("it has a Category");
#line 307
 testRunner.And("it has an Account Out");
#line 308
 testRunner.And("it has no Account In");
#line 309
 testRunner.When("I try to save the move");
#line 310
 testRunner.Then("I will receive this error: MoveDetailValueRequired");
#line 311
 testRunner.And("the move will not be saved");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("91. Save with info all right (Out) (S)")]
        public virtual void _91_SaveWithInfoAllRightOutS()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("91. Save with info all right (Out) (S)", ((string[])(null)));
#line 315
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table28 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value"});
            table28.AddRow(new string[] {
                        "Move Ca91",
                        "2012-03-31",
                        "Out",
                        "10"});
#line 316
 testRunner.Given("I have this move to create", ((string)(null)), table28);
#line 319
 testRunner.And("it has no Details");
#line 320
 testRunner.And("it has a Category");
#line 321
 testRunner.And("it has an Account Out");
#line 322
 testRunner.And("it has no Account In");
#line 323
 testRunner.When("I try to save the move");
#line 324
 testRunner.Then("I will receive no error");
#line 325
 testRunner.And("the move will be saved");
#line 326
 testRunner.And("the month-category-accountOut value will decrease in 10");
#line 327
 testRunner.And("the year-category-accountOut value will decrease in 10");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("92. Save with info all right (In) (S)")]
        public virtual void _92_SaveWithInfoAllRightInS()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("92. Save with info all right (In) (S)", ((string[])(null)));
#line 329
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table29 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value"});
            table29.AddRow(new string[] {
                        "Move Ca92",
                        "2012-03-31",
                        "In",
                        "10"});
#line 330
 testRunner.Given("I have this move to create", ((string)(null)), table29);
#line 333
 testRunner.And("it has no Details");
#line 334
 testRunner.And("it has a Category");
#line 335
 testRunner.And("it has no Account Out");
#line 336
 testRunner.And("it has an Account In");
#line 337
 testRunner.When("I try to save the move");
#line 338
 testRunner.Then("I will receive no error");
#line 339
 testRunner.And("the move will be saved");
#line 340
 testRunner.And("the month-category-accountIn value will increase in 10");
#line 341
 testRunner.And("the year-category-accountIn value will increase in 10");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("93. Save with info all right (Transfer) (S)")]
        public virtual void _93_SaveWithInfoAllRightTransferS()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("93. Save with info all right (Transfer) (S)", ((string[])(null)));
#line 343
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table30 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value"});
            table30.AddRow(new string[] {
                        "Move Ca93",
                        "2012-03-31",
                        "Transfer",
                        "10"});
#line 344
 testRunner.Given("I have this move to create", ((string)(null)), table30);
#line 347
 testRunner.And("it has no Details");
#line 348
 testRunner.And("it has a Category");
#line 349
 testRunner.And("it has an Account Out");
#line 350
 testRunner.And("it has an Account In");
#line 351
 testRunner.When("I try to save the move");
#line 352
 testRunner.Then("I will receive no error");
#line 353
 testRunner.And("the move will be saved");
#line 354
 testRunner.And("the month-category-accountOut value will decrease in 10");
#line 355
 testRunner.And("the year-category-accountOut value will decrease in 10");
#line 356
 testRunner.And("the month-category-accountIn value will increase in 10");
#line 357
 testRunner.And("the year-category-accountIn value will increase in 10");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("94. Save with info all right (value) (S)")]
        public virtual void _94_SaveWithInfoAllRightValueS()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("94. Save with info all right (value) (S)", ((string[])(null)));
#line 359
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table31 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value"});
            table31.AddRow(new string[] {
                        "Move Ca91",
                        "2012-03-31",
                        "Out",
                        "10"});
#line 360
 testRunner.Given("I have this move to create", ((string)(null)), table31);
#line 363
 testRunner.And("it has no Details");
#line 364
 testRunner.And("it has a Category");
#line 365
 testRunner.And("it has an Account Out");
#line 366
 testRunner.And("it has no Account In");
#line 367
 testRunner.When("I try to save the move");
#line 368
 testRunner.Then("I will receive no error");
#line 369
 testRunner.And("the move will be saved");
#line 370
 testRunner.And("the month-category-accountOut value will decrease in 10");
#line 371
 testRunner.And("the year-category-accountOut value will decrease in 10");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("95. Save with info all right (details) (S)")]
        public virtual void _95_SaveWithInfoAllRightDetailsS()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("95. Save with info all right (details) (S)", ((string[])(null)));
#line 373
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table32 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value"});
            table32.AddRow(new string[] {
                        "Move Ca94",
                        "2012-03-31",
                        "Out",
                        ""});
#line 374
 testRunner.Given("I have this move to create", ((string)(null)), table32);
#line hidden
            TechTalk.SpecFlow.Table table33 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Amount",
                        "Value"});
            table33.AddRow(new string[] {
                        "Detail 1",
                        "1",
                        "10"});
            table33.AddRow(new string[] {
                        "Detail 2",
                        "1",
                        "10"});
#line 377
 testRunner.And("the move has this details", ((string)(null)), table33);
#line 381
 testRunner.And("it has a Category");
#line 382
 testRunner.And("it has an Account Out");
#line 383
 testRunner.And("it has no Account In");
#line 384
 testRunner.When("I try to save the move");
#line 385
 testRunner.Then("I will receive no error");
#line 386
 testRunner.And("the move will be saved");
#line 387
 testRunner.And("the month-category-accountOut value will decrease in 20");
#line 388
 testRunner.And("the year-category-accountOut value will decrease in 20");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("96. Save negative (value) (S)")]
        public virtual void _96_SaveNegativeValueS()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("96. Save negative (value) (S)", ((string[])(null)));
#line 390
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table34 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value"});
            table34.AddRow(new string[] {
                        "Move Ca95",
                        "2012-03-31",
                        "Out",
                        "-10"});
#line 391
 testRunner.Given("I have this move to create", ((string)(null)), table34);
#line 394
 testRunner.And("it has no Details");
#line 395
 testRunner.And("it has a Category");
#line 396
 testRunner.And("it has an Account Out");
#line 397
 testRunner.And("it has no Account In");
#line 398
 testRunner.When("I try to save the move");
#line 399
 testRunner.Then("I will receive no error");
#line 400
 testRunner.And("the move will be saved");
#line 401
 testRunner.And("the month-category-accountOut value will decrease in 10");
#line 402
 testRunner.And("the year-category-accountOut value will decrease in 10");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("97. Save negative (details) (S)")]
        public virtual void _97_SaveNegativeDetailsS()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("97. Save negative (details) (S)", ((string[])(null)));
#line 404
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table35 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Date",
                        "Nature",
                        "Value"});
            table35.AddRow(new string[] {
                        "Move Ca96",
                        "2012-03-31",
                        "Out",
                        ""});
#line 405
 testRunner.Given("I have this move to create", ((string)(null)), table35);
#line hidden
            TechTalk.SpecFlow.Table table36 = new TechTalk.SpecFlow.Table(new string[] {
                        "Description",
                        "Amount",
                        "Value"});
            table36.AddRow(new string[] {
                        "Detail 1",
                        "1",
                        "-10"});
            table36.AddRow(new string[] {
                        "Description2",
                        "Amount2",
                        "Value2"});
#line 408
 testRunner.And("the move has this details", ((string)(null)), table36);
#line 412
 testRunner.And("it has a Category");
#line 413
 testRunner.And("it has an Account Out");
#line 414
 testRunner.And("it has no Account In");
#line 415
 testRunner.When("I try to save the move");
#line 416
 testRunner.Then("I will receive no error");
#line 417
 testRunner.And("the move will be saved");
#line 418
 testRunner.And("the month-category-accountOut value will decrease in 20");
#line 419
 testRunner.And("the year-category-accountOut value will decrease in 20");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
