name: Lint commit
on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [ "main" ]
  push:
    branches: [ "14.1.4.2" ]

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Check Title Length
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^[^\n]{7,50}$'
          error: '
            The title is too long, 50 characters are just enough.
            If you have more to say, put it at the message body.
            
            For more explanations:
            https://github.com/darakeon/dfm/blob/main/CONTRIBUTING.md
            '
          # For PR
          excludeTitle: 'true' # PR title
          excludeDescription: 'true' # PR description
          checkAllCommitMessages: 'true'
          accessToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Check Commit Scope
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^(core|auth|law|clip|admin|money|report|outside|attendant|executor|robot|site|api|android|chore|version|docs|tests|tools|security|db|ci|mail|language|publish|accessibility|legal|midna|struct): .+'
          error: '
            The title of the commit message must have the format
            "{scope}: {message in infinitive tense}".
            The valid scopes are: `core`, `auth`, `law`, `clip`,
            `admin`, `money`, `report`, `outside`, `attendant`,
            `executor`, `robot`, `site`, `api`, `android`, `chore`,
            `version`, `docs`, `tests`, `tools`, `security`, `db`,
            `ci`, `mail`, `language`, `publish`, `accessibility`,
            `legal`, `midna`, `struct`
            
            For more explanations:
            https://github.com/darakeon/dfm/blob/main/CONTRIBUTING.md
            '
          # For PR
          excludeTitle: 'true' # PR title
          excludeDescription: 'true' # PR description
          checkAllCommitMessages: 'true'
          accessToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Check Description Length
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^[^\n]{7,50}(?:\n(?:\n[^\n]{0,72})+)?$'
          flags: g
          error: '
            The body can have a longer description than the subject,
            but if you break it in lines with 72 characters,
            it will be easier to read.
            
            For more explanations:
            https://github.com/darakeon/dfm/blob/main/CONTRIBUTING.md
            '
          # For PR
          excludeTitle: 'true' # PR title
          excludeDescription: 'true' # PR description
          checkAllCommitMessages: 'true'
          accessToken: ${{ secrets.GITHUB_TOKEN }}
